package com.yomismtz.expedientedeldentista.ui
import androidx.compose.foundation.layout.*
import androidx.compose.foundation.lazy.*
import androidx.compose.material3.*
import androidx.compose.runtime.*
import androidx.compose.ui.Modifier
import androidx.compose.ui.text.font.FontWeight
import androidx.compose.ui.unit.dp
import com.yomismtz.expedientedeldentista.clinical.DiseaseAnswer
import com.yomismtz.expedientedeldentista.clinical.EducationalSession

private data class Disease37(val id:String,val name:String,val meds:String,val protocol:String)
private data class Category37(val name:String,val diseases:List<Disease37>)
private val categories37=listOf(
 Category37("Endocrinas y metabólicas",listOf(Disease37("dm2","Diabetes mellitus tipo 2","Metformina, insulina u otros antidiabéticos según esquema referido.","diabetes"),Disease37("dm1","Diabetes mellitus tipo 1","Insulina según esquema referido.","diabetes"),Disease37("hypothyroid","Hipotiroidismo","Levotiroxina según esquema referido.","thyroid"),Disease37("hyperthyroid","Hipertiroidismo","Antitiroideos u otros según esquema referido.","thyroid"),Disease37("other_endocrine","Otra","Registrar exactamente lo referido.","general"))),
 Category37("Cardiovasculares",listOf(Disease37("htn","Hipertensión arterial","ARA-II, IECA, calcioantagonistas, diuréticos u otros según esquema referido.","hypertension"),Disease37("arrhythmia","Arritmias","Registrar antiarrítmicos/anticoagulantes referidos.","cardio"),Disease37("ischemic","Cardiopatía isquémica / antecedente de infarto","Registrar antiagregantes, anticoagulantes y cardiológicos referidos.","cardio"),Disease37("heart_failure","Insuficiencia cardiaca","Registrar tratamiento y estado funcional.","cardio"),Disease37("other_cardio","Otra","Registrar exactamente lo referido.","general"))),
 Category37("Respiratorias",listOf(Disease37("asthma","Asma","Inhaladores de rescate/control y otros medicamentos referidos.","respiratory"),Disease37("copd","EPOC","Broncodilatadores, inhaladores y oxígeno si se refiere.","respiratory"),Disease37("other_resp","Otra","Registrar exactamente lo referido.","general"))),
 Category37("Alérgicas e inmunológicas",listOf(Disease37("hiv","VIH / inmunocompromiso","Registrar tratamiento antirretroviral referido, control médico y datos relevantes.","immune"),Disease37("allergy","Alergias a medicamentos, látex o alimentos","Registrar sustancia, reacción y atención requerida.","allergy"),Disease37("immunodeficiency","Inmunodeficiencia / inmunosupresión","Registrar diagnóstico y tratamiento.","immune"),Disease37("other_immune","Otra","Registrar exactamente lo referido.","general"))),
 Category37("Exantemáticas e infecciosas",listOf(Disease37("measles","Sarampión","Registrar edad, manejo recibido y complicaciones.","exanthem"),Disease37("varicella","Varicela","Registrar edad, manejo recibido y complicaciones.","exanthem"),Disease37("rubella","Rubéola","Registrar edad, manejo recibido y complicaciones.","exanthem"),Disease37("mumps","Parotiditis (paperas)","Registrar edad, manejo recibido y complicaciones.","exanthem"),Disease37("other_infectious","Otra","Registrar exactamente lo referido.","general"))),
 Category37("Autoinmunes e inflamatorias",listOf(Disease37("lupus","Lupus eritematoso sistémico","Registrar inmunomoduladores/corticoides referidos.","immune"),Disease37("ra","Artritis reumatoide","Registrar tratamiento inmunomodulador referido.","immune"),Disease37("other_autoimmune","Otra","Registrar exactamente lo referido.","general"))),
 Category37("Osteomioarticulares y óseas",listOf(Disease37("osteoporosis","Osteoporosis / antirresortivos","Precisar fármaco, vía, tiempo de uso e indicación.","bone"),Disease37("paget","Enfermedad de Paget ósea","Registrar localización, tratamiento y seguimiento médico.","bone"),Disease37("osteogenesis","Osteogénesis imperfecta / fragilidad ósea","Registrar diagnóstico, fracturas, tratamiento y seguimiento.","bone"),Disease37("joint","Enfermedad articular","Registrar diagnóstico y tratamiento.","general"),Disease37("other_bone","Otra","Registrar exactamente lo referido.","general"))),
 Category37("Hematológicas",listOf(Disease37("anemia","Anemia","Registrar tipo, tratamiento y controles si se conocen.","hematologic"),Disease37("vitdef","Deficiencias vitamínicas / nutricionales","Precisar deficiencia documentada, causa, tratamiento y controles.","hematologic"),Disease37("bleeding","Trastorno de coagulación / sangrado","Registrar diagnóstico, episodios y tratamiento.","hematologic"),Disease37("other_heme","Otra","Registrar exactamente lo referido.","general"))),
 Category37("Renales",listOf(Disease37("ckd","Enfermedad renal crónica","Registrar estadio, diálisis/trasplante y medicamentos si se conocen.","renal"),Disease37("other_renal","Otra","Registrar exactamente lo referido.","general"))),
 Category37("Gastrointestinales y hepáticas",listOf(Disease37("gerd","Reflujo gastroesofágico","Registrar tratamiento referido.","gi"),Disease37("liver","Hepatitis / cirrosis / enfermedad hepática","Registrar tipo, estado actual y tratamiento.","liver"),Disease37("other_gi","Otra","Registrar exactamente lo referido.","general"))),
 Category37("Neurológicas",listOf(Disease37("epilepsy","Epilepsia / convulsiones","Registrar fármaco, última crisis y control.","neuro"),Disease37("other_neuro","Otra","Registrar exactamente lo referido.","general"))),
 Category37("Neoplásicas",listOf(Disease37("cancer","Cáncer / quimioterapia / radioterapia","Registrar diagnóstico, tratamiento y zona irradiada cuando aplique.","oncology"),Disease37("other_neoplastic","Otra","Registrar exactamente lo referido.","general")))
)
private fun asa37(map:Map<String,DiseaseAnswer>):Int{val a=map.values.filter{it.present};if(a.isEmpty())return 1;if(a.any{it.currentStatus.contains("inestable",true)||it.currentStatus.contains("amenaza",true)||it.currentStatus.contains("sever",true)})return 4;if(a.any{it.currentStatus.contains("mal control",true)||it.complications.isNotBlank()})return 3;return 2}

@Composable fun PathologicalHistory37Screen(lang:String,session:EducationalSession,onSessionChanged:(EducationalSession)->Unit,onProtocols:()->Unit,onBack:()->Unit){
 var category by remember{mutableStateOf<Category37?>(null)};var disease by remember{mutableStateOf<Disease37?>(null)};val saved=session.history.diseases
 LazyColumn(Modifier.fillMaxSize().padding(18.dp),verticalArrangement=Arrangement.spacedBy(12.dp)){
  item{ScreenHeader("Antecedentes personales patológicos",onBack,"Selecciona una clasificación y después una enfermedad. Los datos se guardan solo en la sesión educativa.")}
  item{NoticeCard("ASA es una orientación educativa: depende de gravedad, control, repercusión sistémica y valoración completa; el diagnóstico por sí solo no determina la clase.")}
  item{Card(Modifier.fillMaxWidth(),colors=CardDefaults.cardColors(containerColor=MaterialTheme.colorScheme.secondaryContainer)){Column(Modifier.padding(14.dp)){Text("ASA "+asa37(saved)+" · orientación automática",fontWeight=FontWeight.Black);Text("Debe confirmarse clínicamente y con supervisión docente.")}}}
  if(category==null){items(categories37){x->Card(onClick={category=x},modifier=Modifier.fillMaxWidth()){Column(Modifier.padding(14.dp)){Text(x.name,fontWeight=FontWeight.Bold);Text("Toca para ver enfermedades frecuentes y relevantes")}}}}
  else if(disease==null){item{Button(onClick={category=null}){Text("← Clasificaciones")}};items(category!!.diseases){x->Card(onClick={disease=x},modifier=Modifier.fillMaxWidth()){Column(Modifier.padding(14.dp)){Text(x.name,fontWeight=FontWeight.Bold);if(saved[x.id]?.present==true)Text("✓ Guardado en esta sesión")}}}}
  else{item{DiseaseEditor37(disease!!,saved[disease!!.id]?:DiseaseAnswer(),{a->val n=saved.toMutableMap();n[disease!!.id]=a;onSessionChanged(session.copy(history=session.history.copy(diseases=n,asaClass=asa37(n))));disease=null},onProtocols){disease=null}}}
 }
}
private fun presetTreatments37(d:Disease37):List<String> = when(d.protocol){
 "diabetes" -> listOf("Metformina referida","SGLT2 referido","GLP-1 / GIP-GLP-1 referido","Insulina basal referida","Insulina basal-bolo referida","Combinación de fármacos referida","Cambios de estilo de vida / educación","Otro esquema indicado por su médico","No toma tratamiento")
 "hypertension","cardio" -> listOf("IECA referido","ARA-II referido","Calcioantagonista referido","Diurético referido","Betabloqueador referido","Antiagregante/anticoagulante referido cuando corresponda","Combinación referida","Otro","No toma tratamiento")
 "respiratory" -> listOf("Inhalador de rescate referido","Corticoide inhalado referido","Broncodilatador de acción prolongada referido","Combinación de inhaladores","Oxígeno referido","Otro","No toma tratamiento")
 "thyroid" -> listOf("Levotiroxina referida","Antitiroideo referido","Yodo/radioyodo antecedente","Otro","No toma tratamiento")
 "immune" -> listOf("Inmunomodulador/inmunosupresor referido","Corticoide referido","Antirretroviral referido cuando corresponda","Biológico referido","Otro","No toma tratamiento")
 "bone" -> listOf("Bisfosfonato referido","Denosumab referido","Calcio/vitamina D referidos","Otro tratamiento óseo","No toma tratamiento")
 "hematologic" -> listOf("Hierro referido","Ácido fólico/B12 referido","Anticoagulante referido","Factor/hemoderivado referido","Otro","No toma tratamiento")
 "renal" -> listOf("Tratamiento renal referido","Diálisis","Trasplante + inmunosupresión referida","Otro","No toma tratamiento")
 "liver","gi" -> listOf("Tratamiento gastrointestinal/hepático referido","Antiviral referido cuando corresponda","Protector/antisecretor referido","Otro","No toma tratamiento")
 "neuro" -> listOf("Anticonvulsivante referido","Otro tratamiento neurológico","No toma tratamiento")
 "oncology" -> listOf("Quimioterapia actual/previa","Radioterapia actual/previa","Terapia dirigida/inmunoterapia referida","Seguimiento sin tratamiento activo","Otro")
 "exanthem" -> listOf("Tratamiento sintomático referido","Antiviral referido cuando correspondió","Sin tratamiento / resuelto","Otro")
 else -> listOf("Tratamiento farmacológico referido","Tratamiento no farmacológico referido","Otro","No toma tratamiento")
}
@Composable private fun DiseaseEditor37(d:Disease37,initial:DiseaseAnswer,onSave:(DiseaseAnswer)->Unit,onProtocol:()->Unit,onBack:()->Unit){
 var onset by remember(d.id){mutableStateOf(initial.onset)};var treatment by remember(d.id){mutableStateOf(initial.treatment)};var status by remember(d.id){mutableStateOf(initial.currentStatus)};var complications by remember(d.id){mutableStateOf(initial.complications)}
 val dates=listOf("Diagnóstico este año","1–2 años","3–5 años","6–10 años","Más de 10 años","Desde la infancia","No recuerda")
 val states=listOf("Controlado según seguimiento médico referido","En tratamiento, control no conocido","Descontrolado referido","Suspendió/no toma medicamentos","En estudio / diagnóstico reciente","Resuelto / antecedente, cuando aplique")
 Column(verticalArrangement=Arrangement.spacedBy(9.dp)){
  Button(onClick=onBack){Text("← Enfermedades")};Text(d.name,style=MaterialTheme.typography.headlineSmall,fontWeight=FontWeight.Black)
  Text("1 · ¿Desde cuándo?",fontWeight=FontWeight.Bold);dates.forEach{x->FilterChip(onset==x,{onset=x},{Text(x)},modifier=Modifier.fillMaxWidth())}
  Text("2 · Tratamiento referido",fontWeight=FontWeight.Bold);presetTreatments37(d).forEach{x->FilterChip(treatment==x,{treatment=x},{Text(x)},modifier=Modifier.fillMaxWidth())}
  Text("3 · Estado actual",fontWeight=FontWeight.Bold);states.forEach{x->FilterChip(status==x,{status=x},{Text(x)},modifier=Modifier.fillMaxWidth())}
  OutlinedTextField(complications,{complications=it},label={Text("Complicaciones / observaciones opcionales")},modifier=Modifier.fillMaxWidth())
  if(d.protocol=="diabetes")NoticeCard("En diabetes tipo 2 los estándares actuales recomiendan tratamiento individualizado según metas, comorbilidades cardiovasculares/renales, riesgo de hipoglucemia, tolerancia y preferencias. Estas opciones sirven para registrar lo que el paciente ya usa; no son un esquema automático de prescripción.")
  if(d.protocol=="exanthem")NoticeCard("Registrar edad al padecerla, tratamiento recibido y complicaciones; una imagen aislada no confirma el diagnóstico.")
  Button(enabled=onset.isNotBlank()&&treatment.isNotBlank()&&status.isNotBlank(),onClick={onSave(DiseaseAnswer(true,onset,treatment,status,complications))},modifier=Modifier.fillMaxWidth()){Text("💾 Guardar antecedente")}
  Button(onClick=onProtocol,modifier=Modifier.fillMaxWidth()){Text("📚 Consultar protocolo odontológico")}
 }
}
@Composable fun SystemicProtocols37Screen(lang:String,onBack:()->Unit){
 val p=listOf("Enfermedad de Paget ósea" to "Confirmar diagnóstico, huesos afectados, tratamiento y seguimiento; valorar repercusión maxilofacial y coordinar procedimientos invasivos cuando corresponda.","Osteogénesis imperfecta / fragilidad ósea" to "Registrar fracturas, tratamiento, movilidad y medicamentos; planear transferencias, posicionamiento y procedimientos con precaución y supervisión.","Deficiencias vitamínicas / anemia" to "Precisar diagnóstico, causa, tratamiento y estudios recientes cuando estén indicados; correlacionar con fatiga, mucosa, sangrado/cicatrización sin atribuir hallazgos aislados a una sola causa.","VIH / inmunocompromiso" to "Registrar control médico y tratamiento referido; valorar infecciones/lesiones orales, interacciones y estudios sólo cuando estén clínicamente indicados. Evitar estigma y mantener confidencialidad.","Diabetes mellitus" to "Confirmar control, medicamentos y episodios de hipoglucemia; coordinar alimentación/horario y reconocer urgencias. En pediatría integrar al cuidador y plan médico.","Hipertensión arterial" to "Confirmar diagnóstico, tratamiento, control y signos vitales; valorar interconsulta antes de atención electiva según hallazgos y riesgo.","Trastornos tiroideos" to "Precisar hipo/hipertiroidismo, control y tratamiento; identificar descompensación antes de atención electiva. En menores integrar crecimiento y seguimiento médico.","Asma / EPOC" to "Identificar desencadenantes, gravedad, control, inhaladores y exacerbaciones recientes.","Cardiopatía / anticoagulación" to "Precisar diagnóstico, capacidad funcional y fármacos. No suspender antiagregantes o anticoagulantes por cuenta propia.","Enfermedad renal o hepática" to "Precisar función, diálisis/trasplante, sangrado y medicamentos; revisar estudios pertinentes y coordinar cuando corresponda.","Osteoporosis / antirresortivos" to "Documentar fármaco, vía, duración e indicación antes de procedimientos óseos invasivos.","Epilepsia" to "Registrar control, última crisis, desencadenantes y fármacos; preparar medidas de seguridad.","Cáncer / inmunosupresión" to "Identificar tratamiento activo, alteraciones hematológicas cuando apliquen, radioterapia de cabeza/cuello y coordinación oncológica.")
 LazyColumn(Modifier.fillMaxSize().padding(18.dp),verticalArrangement=Arrangement.spacedBy(12.dp)){item{ScreenHeader("Protocolos para pacientes con enfermedades sistémicas",onBack,"Guía educativa de valoración odontológica; no sustituye interconsulta, juicio clínico ni protocolos institucionales.")};items(p){x->Card(Modifier.fillMaxWidth()){Column(Modifier.padding(14.dp),verticalArrangement=Arrangement.spacedBy(6.dp)){Text(x.first,fontWeight=FontWeight.Black);Text(x.second);Text("Revisar: historia → medicamentos → signos vitales/estudios → control → riesgo → interconsulta → ASA orientativa.",color=MaterialTheme.colorScheme.primary)}}}}
}
