package com.yomismtz.expedientedeldentista.ui
import androidx.compose.foundation.layout.*
import androidx.compose.foundation.lazy.*
import androidx.compose.material3.*
import androidx.compose.runtime.*
import androidx.compose.ui.Modifier
import androidx.compose.ui.text.font.FontWeight
import androidx.compose.ui.unit.dp
import com.yomismtz.expedientedeldentista.clinical.DiseaseAnswer
import com.yomismtz.expedientedeldentista.clinical.EducationalSession

private data class Disease37(val id:String,val name:String,val meds:String,val protocol:String)
private data class Category37(val name:String,val diseases:List<Disease37>)
private fun d37(id:String,name:String,protocol:String="general")=Disease37(id,name,"Registrar tratamiento referido por el paciente.",protocol)
private val categories37=listOf(
 Category37("Endocrinas y metabólicas",listOf(d37("dm1","Diabetes mellitus tipo 1","diabetes"),d37("dm2","Diabetes mellitus tipo 2","diabetes"),d37("prediabetes","Prediabetes","diabetes"),d37("hypothyroid","Hipotiroidismo","thyroid"),d37("hyperthyroid","Hipertiroidismo","thyroid"),d37("hashimoto","Tiroiditis de Hashimoto","thyroid"),d37("obesity","Obesidad"),d37("metabolic","Síndrome metabólico"))),
 Category37("Cardiovasculares",listOf(d37("htn","Hipertensión arterial","hypertension"),d37("ischemic","Cardiopatía isquémica / antecedente de infarto","cardio"),d37("angina","Angina de pecho","cardio"),d37("arrhythmia","Arritmias","cardio"),d37("heart_failure","Insuficiencia cardiaca","cardio"),d37("valvular","Valvulopatía","cardio"),d37("congenital_heart","Cardiopatía congénita","cardio"),d37("stroke","Antecedente de evento cerebrovascular","cardio"))),
 Category37("Respiratorias",listOf(d37("asthma","Asma","respiratory"),d37("copd","EPOC","respiratory"),d37("chronic_bronchitis","Bronquitis crónica","respiratory"),d37("emphysema","Enfisema","respiratory"),d37("sleep_apnea","Apnea obstructiva del sueño","respiratory"),d37("pulmonary_fibrosis","Fibrosis pulmonar","respiratory"),d37("pneumonia","Neumonía recurrente / antecedente relevante","respiratory"),d37("tuberculosis","Tuberculosis","respiratory"))),
 Category37("Alérgicas",listOf(d37("drug_allergy","Alergia a medicamentos","allergy"),d37("latex_allergy","Alergia al látex","allergy"),d37("food_allergy","Alergia alimentaria","allergy"),d37("allergic_rhinitis","Rinitis alérgica","allergy"),d37("urticaria","Urticaria","allergy"),d37("atopic_dermatitis","Dermatitis atópica","allergy"),d37("anaphylaxis","Antecedente de anafilaxia","allergy"),d37("contact_dermatitis","Dermatitis de contacto","allergy"))),
 Category37("Exantemáticas e infecciosas",listOf(d37("measles","Sarampión","exanthem"),d37("rubella","Rubéola","exanthem"),d37("varicella","Varicela","exanthem"),d37("mumps","Parotiditis (paperas)","exanthem"),d37("scarlet","Escarlatina","exanthem"),d37("roseola","Exantema súbito / roséola","exanthem"),d37("fifth","Eritema infeccioso / quinta enfermedad","exanthem"),d37("hfmd","Enfermedad mano-pie-boca","exanthem"))),
 Category37("Autoinmunes",listOf(d37("lupus","Lupus eritematoso sistémico","immune"),d37("ra","Artritis reumatoide","immune"),d37("sjogren","Síndrome de Sjögren","immune"),d37("scleroderma","Esclerosis sistémica / esclerodermia","immune"),d37("psoriasis","Psoriasis / artritis psoriásica","immune"),d37("celiac","Enfermedad celíaca","immune"),d37("multiple_sclerosis","Esclerosis múltiple","immune"),d37("vasculitis","Vasculitis autoinmune","immune"))),
 Category37("Osteomusculares y óseas",listOf(d37("osteoporosis","Osteoporosis","bone"),d37("osteopenia","Osteopenia","bone"),d37("paget","Enfermedad de Paget ósea","bone"),d37("osteogenesis","Osteogénesis imperfecta","bone"),d37("osteoarthritis","Osteoartrosis","bone"),d37("fibromyalgia","Fibromialgia","bone"),d37("muscular_dystrophy","Distrofia muscular","bone"),d37("osteomyelitis","Antecedente de osteomielitis","bone"))),
 Category37("Hematológicas",listOf(d37("iron_anemia","Anemia ferropénica","hematologic"),d37("b12_anemia","Anemia por vitamina B12/folato","hematologic"),d37("sickle","Enfermedad de células falciformes","hematologic"),d37("hemophilia_a","Hemofilia A","hematologic"),d37("hemophilia_b","Hemofilia B","hematologic"),d37("vwd","Enfermedad de von Willebrand","hematologic"),d37("thrombocytopenia","Trombocitopenia","hematologic"),d37("thrombophilia","Trombofilia / antecedente trombótico","hematologic"))),
 Category37("Renales y urinarias",listOf(d37("ckd","Enfermedad renal crónica","renal"),d37("renal_failure","Insuficiencia renal avanzada","renal"),d37("dialysis","Paciente en diálisis","renal"),d37("renal_transplant","Trasplante renal","renal"),d37("glomerulonephritis","Glomerulonefritis","renal"),d37("nephrotic","Síndrome nefrótico","renal"),d37("polycystic","Enfermedad renal poliquística","renal"),d37("recurrent_uti","Infecciones urinarias recurrentes","renal"))),
 Category37("Gastrointestinales y hepáticas",listOf(d37("gerd","Reflujo gastroesofágico","gi"),d37("gastritis","Gastritis","gi"),d37("peptic_ulcer","Úlcera péptica","gi"),d37("celiac_gi","Enfermedad celíaca","gi"),d37("crohn","Enfermedad de Crohn","gi"),d37("ulcerative_colitis","Colitis ulcerosa","gi"),d37("hepatitis","Hepatitis viral / crónica","liver"),d37("cirrhosis","Cirrosis / enfermedad hepática crónica","liver"))),
 Category37("Neurológicas",listOf(d37("epilepsy","Epilepsia / convulsiones","neuro"),d37("migraine","Migraña","neuro"),d37("parkinson","Enfermedad de Parkinson","neuro"),d37("alzheimer","Enfermedad de Alzheimer / demencia","neuro"),d37("multiple_sclerosis_neuro","Esclerosis múltiple","neuro"),d37("neuropathy","Neuropatía periférica","neuro"),d37("cerebral_palsy","Parálisis cerebral","neuro"),d37("stroke_neuro","Secuelas de evento cerebrovascular","neuro"))),
 Category37("Neoplásicas",listOf(d37("oral_cancer","Cáncer oral / orofaríngeo","oncology"),d37("breast_cancer","Cáncer de mama","oncology"),d37("prostate_cancer","Cáncer de próstata","oncology"),d37("lung_cancer","Cáncer pulmonar","oncology"),d37("colorectal_cancer","Cáncer colorrectal","oncology"),d37("leukemia","Leucemia","oncology"),d37("lymphoma","Linfoma","oncology"),d37("myeloma","Mieloma múltiple","oncology"))),
 Category37("VIH e inmunodeficiencias",listOf(d37("hiv","VIH","immune"),d37("aids","VIH con antecedente de enfermedad avanzada/SIDA referido","immune"),d37("primary_immune","Inmunodeficiencia primaria","immune"),d37("transplant_immune","Inmunosupresión por trasplante","immune"),d37("steroid_immune","Inmunosupresión por corticoides","immune"),d37("biologic_immune","Inmunosupresión por terapia biológica","immune"),d37("chemo_immune","Inmunosupresión por quimioterapia","immune"),d37("other_immune","Otra inmunodeficiencia diagnosticada","immune")))
)
private fun asa37(map:Map<String,DiseaseAnswer>):Int{val a=map.values.filter{it.present};if(a.isEmpty())return 1;if(a.any{it.currentStatus.contains("inestable",true)||it.currentStatus.contains("amenaza",true)||it.currentStatus.contains("sever",true)})return 4;if(a.any{it.currentStatus.contains("mal control",true)||it.complications.isNotBlank()})return 3;return 2}

@Composable fun PathologicalHistory37Screen(lang:String,session:EducationalSession,onSessionChanged:(EducationalSession)->Unit,onProtocols:()->Unit,onBack:()->Unit){
 var category by remember{mutableStateOf<Category37?>(null)};var disease by remember{mutableStateOf<Disease37?>(null)};val saved=session.history.diseases
 LazyColumn(Modifier.fillMaxSize().padding(18.dp),verticalArrangement=Arrangement.spacedBy(12.dp)){
  item{ScreenHeader("Antecedentes personales patológicos",onBack,"Selecciona una clasificación y después una enfermedad. Los datos se guardan solo en la sesión educativa.")}
  item{NoticeCard("ASA es una orientación educativa: depende de gravedad, control, repercusión sistémica y valoración completa; el diagnóstico por sí solo no determina la clase.")}
  item{Card(Modifier.fillMaxWidth(),colors=CardDefaults.cardColors(containerColor=MaterialTheme.colorScheme.secondaryContainer)){Column(Modifier.padding(14.dp)){Text("ASA "+asa37(saved)+" · orientación automática",fontWeight=FontWeight.Black);Text("Debe confirmarse clínicamente y con supervisión docente.")}}}
  if(category==null){items(categories37){x->Card(onClick={category=x},modifier=Modifier.fillMaxWidth()){Column(Modifier.padding(14.dp)){Text(x.name,fontWeight=FontWeight.Bold);Text("Toca para ver enfermedades frecuentes y relevantes")}}}}
  else if(disease==null){item{Button(onClick={category=null}){Text("← Clasificaciones")}};items(category!!.diseases){x->Card(onClick={disease=x},modifier=Modifier.fillMaxWidth()){Column(Modifier.padding(14.dp)){Text(x.name,fontWeight=FontWeight.Bold);if(saved[x.id]?.present==true)Text("✓ Guardado en esta sesión")}}}}
  else{item{DiseaseEditor37(disease!!,saved[disease!!.id]?:DiseaseAnswer(),{a->val n=saved.toMutableMap();n[disease!!.id]=a;onSessionChanged(session.copy(history=session.history.copy(diseases=n,asaClass=asa37(n))));disease=null},onProtocols){disease=null}}}
 }
}
private fun presetTreatments37(d:Disease37):List<String> = when(d.protocol){
 "diabetes" -> listOf("Metformina referida","SGLT2 referido","GLP-1 / GIP-GLP-1 referido","Insulina basal referida","Insulina basal-bolo referida","Combinación de fármacos referida","Cambios de estilo de vida / educación","Otro esquema indicado por su médico","No toma tratamiento")
 "hypertension","cardio" -> listOf("IECA referido","ARA-II referido","Calcioantagonista referido","Diurético referido","Betabloqueador referido","Antiagregante/anticoagulante referido cuando corresponda","Combinación referida","Otro","No toma tratamiento")
 "respiratory" -> listOf("Inhalador de rescate referido","Corticoide inhalado referido","Broncodilatador de acción prolongada referido","Combinación de inhaladores","Oxígeno referido","Otro","No toma tratamiento")
 "thyroid" -> listOf("Levotiroxina referida","Antitiroideo referido","Yodo/radioyodo antecedente","Otro","No toma tratamiento")
 "immune" -> listOf("Inmunomodulador/inmunosupresor referido","Corticoide referido","Antirretroviral referido cuando corresponda","Biológico referido","Otro","No toma tratamiento")
 "bone" -> listOf("Bisfosfonato referido","Denosumab referido","Calcio/vitamina D referidos","Otro tratamiento óseo","No toma tratamiento")
 "hematologic" -> listOf("Hierro referido","Ácido fólico/B12 referido","Anticoagulante referido","Factor/hemoderivado referido","Otro","No toma tratamiento")
 "renal" -> listOf("Tratamiento renal referido","Diálisis","Trasplante + inmunosupresión referida","Otro","No toma tratamiento")
 "liver","gi" -> listOf("Tratamiento gastrointestinal/hepático referido","Antiviral referido cuando corresponda","Protector/antisecretor referido","Otro","No toma tratamiento")
 "neuro" -> listOf("Anticonvulsivante referido","Otro tratamiento neurológico","No toma tratamiento")
 "oncology" -> listOf("Quimioterapia actual/previa","Radioterapia actual/previa","Terapia dirigida/inmunoterapia referida","Seguimiento sin tratamiento activo","Otro")
 "exanthem" -> listOf("Tratamiento sintomático referido","Antiviral referido cuando correspondió","Sin tratamiento / resuelto","Otro")
 else -> listOf("Tratamiento farmacológico referido","Tratamiento no farmacológico referido","Otro","No toma tratamiento")
}
@Composable private fun DiseaseEditor37(d:Disease37,initial:DiseaseAnswer,onSave:(DiseaseAnswer)->Unit,onProtocol:()->Unit,onBack:()->Unit){
 var onset by remember(d.id){mutableStateOf(initial.onset)};var treatment by remember(d.id){mutableStateOf(initial.treatment)};var status by remember(d.id){mutableStateOf(initial.currentStatus)};var complications by remember(d.id){mutableStateOf(initial.complications)}
 val dates=listOf("Diagnóstico este año","1–2 años","3–5 años","6–10 años","Más de 10 años","Desde la infancia","No recuerda")
 val states=listOf("Controlado según seguimiento médico referido","Descontrolado referido","En tratamiento, control no conocido","Sin tratamiento actualmente","Suspendió tratamiento","En estudio / diagnóstico reciente","Resuelto / antecedente, cuando aplique","No sabe")
 Column(verticalArrangement=Arrangement.spacedBy(9.dp)){
  Button(onClick=onBack){Text("← Enfermedades")};Text(d.name,style=MaterialTheme.typography.headlineSmall,fontWeight=FontWeight.Black)
  Text("1 · ¿Desde cuándo?",fontWeight=FontWeight.Bold);dates.forEach{x->FilterChip(onset==x,{onset=x},{Text(x)},modifier=Modifier.fillMaxWidth())}
  Text("2 · Tratamiento referido",fontWeight=FontWeight.Bold);presetTreatments37(d).forEach{x->FilterChip(treatment==x,{treatment=x},{Text(x)},modifier=Modifier.fillMaxWidth())}
  Text("3 · Estado actual",fontWeight=FontWeight.Bold);states.forEach{x->FilterChip(status==x,{status=x},{Text(x)},modifier=Modifier.fillMaxWidth())}
  Text("4 · Complicaciones referidas",fontWeight=FontWeight.Bold);listOf("Ninguna referida","Sí, en seguimiento","Sí, antecedente resuelto","No sabe / no recuerda").forEach{x->FilterChip(complications==x,{complications=x},{Text(x)},modifier=Modifier.fillMaxWidth())}
  if(d.protocol=="diabetes")NoticeCard("En diabetes tipo 2 los estándares actuales recomiendan tratamiento individualizado según metas, comorbilidades cardiovasculares/renales, riesgo de hipoglucemia, tolerancia y preferencias. Estas opciones sirven para registrar lo que el paciente ya usa; no son un esquema automático de prescripción.")
  if(d.protocol=="exanthem")NoticeCard("Registrar edad al padecerla, tratamiento recibido y complicaciones; una imagen aislada no confirma el diagnóstico.")
  Button(enabled=onset.isNotBlank()&&treatment.isNotBlank()&&status.isNotBlank(),onClick={onSave(DiseaseAnswer(true,onset,treatment,status,complications))},modifier=Modifier.fillMaxWidth()){Text("💾 Guardar antecedente")}
  Button(onClick=onProtocol,modifier=Modifier.fillMaxWidth()){Text("📚 Consultar protocolo odontológico")}
 }
}
@Composable fun SystemicProtocols37Screen(lang:String,onBack:()->Unit){
 val p=listOf("Enfermedad de Paget ósea" to "Confirmar diagnóstico, huesos afectados, tratamiento y seguimiento; valorar repercusión maxilofacial y coordinar procedimientos invasivos cuando corresponda.","Osteogénesis imperfecta / fragilidad ósea" to "Registrar fracturas, tratamiento, movilidad y medicamentos; planear transferencias, posicionamiento y procedimientos con precaución y supervisión.","Deficiencias vitamínicas / anemia" to "Precisar diagnóstico, causa, tratamiento y estudios recientes cuando estén indicados; correlacionar con fatiga, mucosa, sangrado/cicatrización sin atribuir hallazgos aislados a una sola causa.","VIH / inmunocompromiso" to "Registrar control médico y tratamiento referido; valorar infecciones/lesiones orales, interacciones y estudios sólo cuando estén clínicamente indicados. Evitar estigma y mantener confidencialidad.","Diabetes mellitus" to "Confirmar control, medicamentos y episodios de hipoglucemia; coordinar alimentación/horario y reconocer urgencias. En pediatría integrar al cuidador y plan médico.","Hipertensión arterial" to "Confirmar diagnóstico, tratamiento, control y signos vitales; valorar interconsulta antes de atención electiva según hallazgos y riesgo.","Trastornos tiroideos" to "Precisar hipo/hipertiroidismo, control y tratamiento; identificar descompensación antes de atención electiva. En menores integrar crecimiento y seguimiento médico.","Asma / EPOC" to "Identificar desencadenantes, gravedad, control, inhaladores y exacerbaciones recientes.","Cardiopatía / anticoagulación" to "Precisar diagnóstico, capacidad funcional y fármacos. No suspender antiagregantes o anticoagulantes por cuenta propia.","Enfermedad renal o hepática" to "Precisar función, diálisis/trasplante, sangrado y medicamentos; revisar estudios pertinentes y coordinar cuando corresponda.","Osteoporosis / antirresortivos" to "Documentar fármaco, vía, duración e indicación antes de procedimientos óseos invasivos.","Epilepsia" to "Registrar control, última crisis, desencadenantes y fármacos; preparar medidas de seguridad.","Cáncer / inmunosupresión" to "Identificar tratamiento activo, alteraciones hematológicas cuando apliquen, radioterapia de cabeza/cuello y coordinación oncológica.")
 LazyColumn(Modifier.fillMaxSize().padding(18.dp),verticalArrangement=Arrangement.spacedBy(12.dp)){item{ScreenHeader("Protocolos para pacientes con enfermedades sistémicas",onBack,"Guía educativa de valoración odontológica; no sustituye interconsulta, juicio clínico ni protocolos institucionales.")};items(p){x->Card(Modifier.fillMaxWidth()){Column(Modifier.padding(14.dp),verticalArrangement=Arrangement.spacedBy(6.dp)){Text(x.first,fontWeight=FontWeight.Black);Text(x.second);Text("Revisar: historia → medicamentos → signos vitales/estudios → control → riesgo → interconsulta → ASA orientativa.",color=MaterialTheme.colorScheme.primary)}}}}
}
