package com.yomismtz.expedientedeldentista.ui

import androidx.compose.foundation.layout.Arrangement
import androidx.compose.foundation.layout.Column
import androidx.compose.foundation.layout.Row
import androidx.compose.foundation.layout.fillMaxSize
import androidx.compose.foundation.layout.fillMaxWidth
import androidx.compose.foundation.layout.padding
import androidx.compose.foundation.lazy.LazyColumn
import androidx.compose.foundation.lazy.items
import androidx.compose.material3.Card
import androidx.compose.material3.CardDefaults
import androidx.compose.material3.FilterChip
import androidx.compose.material3.MaterialTheme
import androidx.compose.material3.Text
import androidx.compose.runtime.Composable
import androidx.compose.runtime.getValue
import androidx.compose.runtime.mutableStateOf
import androidx.compose.runtime.remember
import androidx.compose.runtime.setValue
import androidx.compose.ui.Modifier
import androidx.compose.ui.text.font.FontWeight
import androidx.compose.ui.unit.dp
import com.yomismtz.expedientedeldentista.clinical.ClinicalContent
import com.yomismtz.expedientedeldentista.clinical.ClinicalEngines
import com.yomismtz.expedientedeldentista.clinical.EducationalSession
import com.yomismtz.expedientedeldentista.clinical.ToothRecord

@Composable
fun TreatmentScreen(lang: String, session: EducationalSession, onSessionChanged: (EducationalSession) -> Unit, onBack: () -> Unit) {
    var selectedTooth by remember { mutableStateOf(16) }
    var primary by remember { mutableStateOf(false) }
    val shown = if (primary) ClinicalContent.primaryTeeth else ClinicalContent.permanentTeeth
    if (selectedTooth !in shown) selectedTooth = shown.first()
    val record = session.teeth[selectedTooth] ?: ToothRecord()
    val selectedPlan = ClinicalContent.treatmentPlans.firstOrNull { it.id == record.diagnosisId }
    val selectedOption = selectedPlan?.options?.firstOrNull { it.id == record.treatmentId }

    fun updateRecord(updated: ToothRecord) {
        onSessionChanged(session.copy(teeth=session.teeth+(selectedTooth to updated),presentTeeth=session.presentTeeth+selectedTooth))
    }

    LazyColumn(Modifier.fillMaxSize().padding(18.dp),verticalArrangement=Arrangement.spacedBy(12.dp)) {
        item { ScreenHeader(tr(lang,"Diagnóstico y tratamiento por diente","Diagnosis and treatment by tooth"),onBack,
            tr(lang,"Relaciona un diagnóstico educativo con tres alternativas y revisa por qué una puede ser preferible en el escenario didáctico.","Relate a teaching diagnosis to three alternatives and review why one may be preferred in the teaching scenario.")) }
        item { Row(horizontalArrangement=Arrangement.spacedBy(8.dp)) {
            FilterChip(!primary,{primary=false},{Text(tr(lang,"Permanentes","Permanent"))});FilterChip(primary,{primary=true},{Text(tr(lang,"Temporales","Primary"))})
        } }
        item { SectionCard(tr(lang,"1 · Elige el diente","1 · Choose the tooth")) { DentalArchSelector(shown,selectedTooth,{selectedTooth=it}){session.teeth[it]?.diagnosisId!=null} } }
        item { SectionCard(tr(lang,"2 · Diagnóstico","2 · Diagnosis")) {
            ClinicalContent.treatmentPlans.forEach { plan -> FilterChip(record.diagnosisId==plan.id,{updateRecord(record.copy(diagnosisId=plan.id,treatmentId=null))},{Text(if(lang=="en")plan.diagnosisEn else plan.diagnosisEs)},modifier=Modifier.fillMaxWidth()) }
        } }
        if(selectedPlan!=null) item { SectionCard(tr(lang,"3 · Compara tres alternativas","3 · Compare three alternatives")) {
            selectedPlan.options.forEachIndexed { i,option ->
                Card(modifier=Modifier.fillMaxWidth(),onClick={updateRecord(record.copy(treatmentId=option.id))},colors=CardDefaults.cardColors(containerColor=if(record.treatmentId==option.id)MaterialTheme.colorScheme.primaryContainer else MaterialTheme.colorScheme.surface)) {
                    Column(Modifier.padding(14.dp),verticalArrangement=Arrangement.spacedBy(5.dp)) {
                        Text("${i+1}. ${if(lang=="en")option.labelEn else option.labelEs}",fontWeight=FontWeight.Bold)
                        Text(if(lang=="en")option.explanationEn else option.explanationEs)
                        if(record.treatmentId==option.id) Text(if(option.preferred)tr(lang,"✓ Preferible en este escenario educativo","✓ Preferred in this teaching scenario") else tr(lang,"△ Alternativa posible según indicación","△ Possible alternative depending on indication"),color=MaterialTheme.colorScheme.primary,fontWeight=FontWeight.Bold)
                    }
                }
            }
        } }
        if(selectedOption!=null) item { NoticeCard(tr(lang,"La elección clínica real requiere diagnóstico completo, restaurabilidad, edad/dentición, pronóstico, condiciones sistémicas, preferencias y supervisión. La app enseña razonamiento, no prescribe.","Real clinical selection requires complete diagnosis, restorability, age/dentition, prognosis, systemic conditions, preferences and supervision. The app teaches reasoning; it does not prescribe.")) }
        item { SectionCard(tr(lang,"Ortodoncia preventiva / mantenimiento de espacio","Preventive orthodontics / space maintenance")) {
            Text("🧭 ${ClinicalEngines.orthodonticSuggestion(session,lang)}")
            Text(tr(lang,"Ante pérdida prematura en dentición temporal se recuerda valorar edad, diente sucesor, erupción, espacio, oclusión y radiografía antes de considerar un aparato.","With premature loss in primary dentition, assess age, successor tooth, eruption, space, occlusion and imaging before considering an appliance."))
        } }
    }
}

private data class NoteTemplate(val titleEs:String,val titleEn:String,val textEs:String,val textEn:String)

private fun noteLibrary():List<NoteTemplate> = listOf(
    NoteTemplate("Ingreso / integración de expediente","Admission / record integration",
        "Paciente consciente, orientado y cooperador. Se revisan antecedentes y signos vitales pertinentes, se realiza exploración regional e intraoral y se integran auxiliares indicados. Se explican diagnóstico presuntivo, plan por fases y documentos de consentimiento. Registrar únicamente lo realmente realizado y los hallazgos obtenidos.",
        "Patient conscious, oriented and cooperative. Relevant history and vital signs are reviewed; regional/intraoral examination and indicated aids are integrated. Presumptive diagnosis, phased plan and consent documents are explained. Record only what was actually performed and found."),
    NoteTemplate("Alta","Discharge",
        "Se verifica la culminación de las fases previstas y el estado clínico al cierre del tratamiento. Documentar síntomas, tejidos, función, higiene, restauraciones, indicaciones de mantenimiento y fecha sugerida de revisión. Especificar si quedan condiciones en vigilancia o remisiones pendientes.",
        "Verify completion of planned phases and clinical status at closure. Document symptoms, tissues, function, hygiene, restorations, maintenance instructions and suggested review date. State any conditions under surveillance or pending referrals."),
    NoteTemplate("Baja / inasistencia / remisión","Discontinuation / nonattendance / referral",
        "Anotar fecha, motivo objetivo de la baja o remisión, estado en que queda el tratamiento, comunicaciones realizadas, riesgos explicados por no continuar y destino de la referencia cuando corresponda. Evitar juicios personales.",
        "Record date, objective reason for discontinuation/referral, treatment status, communications, explained risks of noncompletion and referral destination when applicable. Avoid personal judgments."),
    NoteTemplate("Profilaxis con pasta","Rubber-cup prophylaxis",
        "Registrar evaluación previa, superficies tratadas, remoción de biopelícula/manchas mediante profilaxis indicada, tolerancia, hallazgos posteriores e instrucciones de higiene. Si se aplica flúor, anotar producto/protocolo conforme a la clínica.",
        "Record preassessment, treated surfaces, indicated plaque/stain removal, tolerance, post-procedure findings and hygiene instructions. If fluoride is applied, document product/protocol according to the clinic."),
    NoteTemplate("Limpieza ultrasónica / destartraje","Ultrasonic scaling",
        "Documentar zonas con cálculo, instrumental ultrasónico/manual empleado según protocolo, irrigación, respuesta de tejidos, sangrado relevante, reevaluación al sondaje e instrucciones de higiene/mantenimiento.",
        "Document calculus areas, ultrasonic/manual instrumentation per protocol, irrigation, tissue response, relevant bleeding, probing reassessment and hygiene/maintenance instructions."),
    NoteTemplate("Resina compuesta","Composite resin",
        "OD __. Diagnóstico __. Registrar aislamiento, remoción de tejido indicado, preparación/conservación de estructura, protocolo adhesivo y material conforme al fabricante, técnica de colocación, ajuste de contactos/oclusión, acabado-pulido y ausencia/presencia de incidentes.",
        "Tooth __. Diagnosis __. Record isolation, indicated tissue removal, preparation/conservation of tooth structure, adhesive protocol/material per manufacturer, placement technique, contact/occlusion adjustment, finishing/polishing and incidents."),
    NoteTemplate("Amalgama","Amalgam",
        "OD __. Registrar indicación académica, aislamiento, preparación cavitaria, protección pulpar/base cuando proceda, inserción y conformación del material, ajuste oclusal y recomendaciones. Señalar claramente el material realmente utilizado.",
        "Tooth __. Record academic indication, isolation, preparation, pulp protection/base when applicable, material placement/contouring, occlusal adjustment and instructions. Clearly state the material actually used."),
    NoteTemplate("Incrustación / onlay","Inlay / onlay",
        "OD __. Registrar diagnóstico/restaurabilidad, preparación conservadora, protección pulpar si procede, impresión o escaneo, provisional cuando corresponda, prueba de restauración, adaptación/contactos, protocolo de cementación adhesiva según material/fabricante, oclusión y acabado.",
        "Tooth __. Record diagnosis/restorability, conservative preparation, pulp protection if applicable, impression/scan, provisionalization when applicable, restoration try-in, adaptation/contacts, bonding/cementation protocol per material/manufacturer, occlusion and finishing."),
    NoteTemplate("Corona","Crown",
        "OD __. Registrar diagnóstico, condición pulpar/periodontal, reducción y terminación de preparación, impresión/escaneo, provisional, prueba clínica, contactos y oclusión, selección de material/color, cementación definitiva y controles posteriores.",
        "Tooth __. Record diagnosis, pulpal/periodontal condition, preparation reduction/finish line, impression/scan, provisional, clinical try-in, contacts/occlusion, material/shade, definitive cementation and follow-up."),
    NoteTemplate("Pulpotomía","Pulpotomy",
        "OD __. Registrar diagnóstico pulpar/periapical, anestesia cuando corresponda, aislamiento absoluto, acceso, remoción de pulpa cameral, control de hemorragia y evaluación del tejido, biomaterial empleado según protocolo, sellado/restauración y plan de seguimiento.",
        "Tooth __. Record pulpal/periapical diagnosis, anesthesia when applicable, rubber-dam isolation, access, coronal pulp removal, bleeding control/tissue assessment, biomaterial per protocol, seal/restoration and follow-up plan."),
    NoteTemplate("Pulpectomía","Pulpectomy",
        "OD __. Registrar diagnóstico, aislamiento, acceso/localización de conductos, longitud de trabajo/conductometría según protocolo, preparación e irrigación segura, secado, material de obturación apropiado a dentición/indicación, sellado coronal y control.",
        "Tooth __. Record diagnosis, isolation, access/canal location, working length per protocol, preparation and safe irrigation, drying, filling material appropriate to dentition/indication, coronal seal and control."),
    NoteTemplate("Tratamiento de conductos","Root-canal treatment",
        "OD __. Anotar diagnóstico pulpar y periapical, pruebas relevantes, aislamiento absoluto, acceso, conductometría, preparación biomecánica e irrigación conforme al protocolo, obturación, radiografía/control indicado, sellado coronal y plan restaurador.",
        "Tooth __. Record pulpal/periapical diagnosis, relevant tests, rubber-dam isolation, access, working length, biomechanical preparation/irrigation per protocol, obturation, indicated control imaging, coronal seal and restorative plan."),
    NoteTemplate("Exodoncia simple","Simple extraction",
        "OD __. Registrar indicación, consentimiento, revisión de riesgo, anestesia y técnica bajo supervisión, hallazgos transoperatorios, integridad de la pieza/raíces, hemostasia, estado del alvéolo, incidentes y recomendaciones posoperatorias/signos de alarma.",
        "Tooth __. Record indication, consent, risk review, anesthesia/technique under supervision, intraoperative findings, tooth/root integrity, hemostasis, socket status, incidents and postoperative instructions/warning signs."),
    NoteTemplate("Cirugía menor","Minor oral surgery",
        "Registrar diagnóstico e indicación, sitio, estudios revisados, consentimiento, anestesia, abordaje realizado, hallazgos, tejido enviado a estudio cuando corresponda, hemostasia/sutura, complicaciones, indicaciones y cita de control.",
        "Record diagnosis/indication, site, studies reviewed, consent, anesthesia, approach, findings, tissue submitted for examination when applicable, hemostasis/suture, complications, instructions and follow-up."),
    NoteTemplate("Sellador de fosetas y fisuras","Pit and fissure sealant",
        "OD/superficie __. Registrar evaluación de la superficie, aislamiento, limpieza/preparación, material y protocolo del fabricante, colocación, polimerización cuando aplique, revisión de retención y oclusión, e indicación de control.",
        "Tooth/surface __. Record surface assessment, isolation, cleaning/preparation, material/manufacturer protocol, placement, curing when applicable, retention/occlusion check and recall."),
    NoteTemplate("Ionómero / restauración provisional","Glass ionomer / provisional restoration",
        "OD __. Registrar motivo de provisionalización o indicación del material, control de humedad, preparación, acondicionamiento si aplica, colocación, contorno, ajuste oclusal y plan para reevaluación/restauración definitiva.",
        "Tooth __. Record reason for provisionalization/material indication, moisture control, preparation, conditioning if applicable, placement, contour, occlusal adjustment and definitive reassessment plan."),
    NoteTemplate("Mantenedor de espacio","Space maintainer",
        "Registrar diente perdido, edad/dentición, valoración de espacio y sucesor, tipo de mantenedor indicado en el escenario educativo, prueba/adaptación, cementación o entrega, oclusión, higiene y calendario de revisión.",
        "Record missing tooth, age/dentition, space/successor assessment, teaching-scenario appliance type, try-in/adaptation, cementation/delivery, occlusion, hygiene and recall schedule.")
)


private fun supplementalNoteLibraryV39():List<NoteTemplate> = listOf(
    NoteTemplate("Exploración peribucal e intrabucal","Exploración peribucal e intrabucal","Registrar fecha, motivo, OD o zona, hallazgos previos, diagnóstico relacionado, procedimiento de exploración peribucal e intrabucal realizado conforme al protocolo docente, materiales o anestesia cuando aplique, respuesta del paciente, incidentes, indicaciones y plan de seguimiento. Documentar únicamente lo que realmente se efectuó.","Record date, reason, tooth/site, pre-procedure findings, related diagnosis, exploración peribucal e intrabucal procedure performed according to the teaching protocol, materials or anesthesia when applicable, patient response, incidents, instructions and follow-up. Document only what was actually performed."),
    NoteTemplate("Control de signos vitales","Control de signos vitales","Registrar fecha, motivo, OD o zona, hallazgos previos, diagnóstico relacionado, procedimiento de control de signos vitales realizado conforme al protocolo docente, materiales o anestesia cuando aplique, respuesta del paciente, incidentes, indicaciones y plan de seguimiento. Documentar únicamente lo que realmente se efectuó.","Record date, reason, tooth/site, pre-procedure findings, related diagnosis, control de signos vitales procedure performed according to the teaching protocol, materials or anesthesia when applicable, patient response, incidents, instructions and follow-up. Document only what was actually performed."),
    NoteTemplate("Control de placa dentobacteriana","Control de placa dentobacteriana","Registrar fecha, motivo, OD o zona, hallazgos previos, diagnóstico relacionado, procedimiento de control de placa dentobacteriana realizado conforme al protocolo docente, materiales o anestesia cuando aplique, respuesta del paciente, incidentes, indicaciones y plan de seguimiento. Documentar únicamente lo que realmente se efectuó.","Record date, reason, tooth/site, pre-procedure findings, related diagnosis, control de placa dentobacteriana procedure performed according to the teaching protocol, materials or anesthesia when applicable, patient response, incidents, instructions and follow-up. Document only what was actually performed."),
    NoteTemplate("Índice O’Leary","Índice O’Leary","Registrar fecha, motivo, OD o zona, hallazgos previos, diagnóstico relacionado, procedimiento de índice o’leary realizado conforme al protocolo docente, materiales o anestesia cuando aplique, respuesta del paciente, incidentes, indicaciones y plan de seguimiento. Documentar únicamente lo que realmente se efectuó.","Record date, reason, tooth/site, pre-procedure findings, related diagnosis, índice o’leary procedure performed according to the teaching protocol, materials or anesthesia when applicable, patient response, incidents, instructions and follow-up. Document only what was actually performed."),
    NoteTemplate("IHOS","IHOS","Registrar fecha, motivo, OD o zona, hallazgos previos, diagnóstico relacionado, procedimiento de ihos realizado conforme al protocolo docente, materiales o anestesia cuando aplique, respuesta del paciente, incidentes, indicaciones y plan de seguimiento. Documentar únicamente lo que realmente se efectuó.","Record date, reason, tooth/site, pre-procedure findings, related diagnosis, ihos procedure performed according to the teaching protocol, materials or anesthesia when applicable, patient response, incidents, instructions and follow-up. Document only what was actually performed."),
    NoteTemplate("IPC","IPC","Registrar fecha, motivo, OD o zona, hallazgos previos, diagnóstico relacionado, procedimiento de ipc realizado conforme al protocolo docente, materiales o anestesia cuando aplique, respuesta del paciente, incidentes, indicaciones y plan de seguimiento. Documentar únicamente lo que realmente se efectuó.","Record date, reason, tooth/site, pre-procedure findings, related diagnosis, ipc procedure performed according to the teaching protocol, materials or anesthesia when applicable, patient response, incidents, instructions and follow-up. Document only what was actually performed."),
    NoteTemplate("Periodontograma","Periodontograma","Registrar fecha, motivo, OD o zona, hallazgos previos, diagnóstico relacionado, procedimiento de periodontograma realizado conforme al protocolo docente, materiales o anestesia cuando aplique, respuesta del paciente, incidentes, indicaciones y plan de seguimiento. Documentar únicamente lo que realmente se efectuó.","Record date, reason, tooth/site, pre-procedure findings, related diagnosis, periodontograma procedure performed according to the teaching protocol, materials or anesthesia when applicable, patient response, incidents, instructions and follow-up. Document only what was actually performed."),
    NoteTemplate("Aplicación tópica de flúor","Aplicación tópica de flúor","Registrar fecha, motivo, OD o zona, hallazgos previos, diagnóstico relacionado, procedimiento de aplicación tópica de flúor realizado conforme al protocolo docente, materiales o anestesia cuando aplique, respuesta del paciente, incidentes, indicaciones y plan de seguimiento. Documentar únicamente lo que realmente se efectuó.","Record date, reason, tooth/site, pre-procedure findings, related diagnosis, aplicación tópica de flúor procedure performed according to the teaching protocol, materials or anesthesia when applicable, patient response, incidents, instructions and follow-up. Document only what was actually performed."),
    NoteTemplate("Barniz de flúor","Barniz de flúor","Registrar fecha, motivo, OD o zona, hallazgos previos, diagnóstico relacionado, procedimiento de barniz de flúor realizado conforme al protocolo docente, materiales o anestesia cuando aplique, respuesta del paciente, incidentes, indicaciones y plan de seguimiento. Documentar únicamente lo que realmente se efectuó.","Record date, reason, tooth/site, pre-procedure findings, related diagnosis, barniz de flúor procedure performed according to the teaching protocol, materials or anesthesia when applicable, patient response, incidents, instructions and follow-up. Document only what was actually performed."),
    NoteTemplate("Instrucción de técnica de cepillado","Instrucción de técnica de cepillado","Registrar fecha, motivo, OD o zona, hallazgos previos, diagnóstico relacionado, procedimiento de instrucción de técnica de cepillado realizado conforme al protocolo docente, materiales o anestesia cuando aplique, respuesta del paciente, incidentes, indicaciones y plan de seguimiento. Documentar únicamente lo que realmente se efectuó.","Record date, reason, tooth/site, pre-procedure findings, related diagnosis, instrucción de técnica de cepillado procedure performed according to the teaching protocol, materials or anesthesia when applicable, patient response, incidents, instructions and follow-up. Document only what was actually performed."),
    NoteTemplate("Instrucción de hilo dental","Instrucción de hilo dental","Registrar fecha, motivo, OD o zona, hallazgos previos, diagnóstico relacionado, procedimiento de instrucción de hilo dental realizado conforme al protocolo docente, materiales o anestesia cuando aplique, respuesta del paciente, incidentes, indicaciones y plan de seguimiento. Documentar únicamente lo que realmente se efectuó.","Record date, reason, tooth/site, pre-procedure findings, related diagnosis, instrucción de hilo dental procedure performed according to the teaching protocol, materials or anesthesia when applicable, patient response, incidents, instructions and follow-up. Document only what was actually performed."),
    NoteTemplate("Control de dieta cariogénica","Control de dieta cariogénica","Registrar fecha, motivo, OD o zona, hallazgos previos, diagnóstico relacionado, procedimiento de control de dieta cariogénica realizado conforme al protocolo docente, materiales o anestesia cuando aplique, respuesta del paciente, incidentes, indicaciones y plan de seguimiento. Documentar únicamente lo que realmente se efectuó.","Record date, reason, tooth/site, pre-procedure findings, related diagnosis, control de dieta cariogénica procedure performed according to the teaching protocol, materials or anesthesia when applicable, patient response, incidents, instructions and follow-up. Document only what was actually performed."),
    NoteTemplate("Diagnóstico ICDAS","Diagnóstico ICDAS","Registrar fecha, motivo, OD o zona, hallazgos previos, diagnóstico relacionado, procedimiento de diagnóstico icdas realizado conforme al protocolo docente, materiales o anestesia cuando aplique, respuesta del paciente, incidentes, indicaciones y plan de seguimiento. Documentar únicamente lo que realmente se efectuó.","Record date, reason, tooth/site, pre-procedure findings, related diagnosis, diagnóstico icdas procedure performed according to the teaching protocol, materials or anesthesia when applicable, patient response, incidents, instructions and follow-up. Document only what was actually performed."),
    NoteTemplate("Odontograma de ingreso","Odontograma de ingreso","Registrar fecha, motivo, OD o zona, hallazgos previos, diagnóstico relacionado, procedimiento de odontograma de ingreso realizado conforme al protocolo docente, materiales o anestesia cuando aplique, respuesta del paciente, incidentes, indicaciones y plan de seguimiento. Documentar únicamente lo que realmente se efectuó.","Record date, reason, tooth/site, pre-procedure findings, related diagnosis, odontograma de ingreso procedure performed according to the teaching protocol, materials or anesthesia when applicable, patient response, incidents, instructions and follow-up. Document only what was actually performed."),
    NoteTemplate("Restauración preventiva de resina","Restauración preventiva de resina","Registrar fecha, motivo, OD o zona, hallazgos previos, diagnóstico relacionado, procedimiento de restauración preventiva de resina realizado conforme al protocolo docente, materiales o anestesia cuando aplique, respuesta del paciente, incidentes, indicaciones y plan de seguimiento. Documentar únicamente lo que realmente se efectuó.","Record date, reason, tooth/site, pre-procedure findings, related diagnosis, restauración preventiva de resina procedure performed according to the teaching protocol, materials or anesthesia when applicable, patient response, incidents, instructions and follow-up. Document only what was actually performed."),
    NoteTemplate("Resina Clase I","Resina Clase I","Registrar fecha, motivo, OD o zona, hallazgos previos, diagnóstico relacionado, procedimiento de resina clase i realizado conforme al protocolo docente, materiales o anestesia cuando aplique, respuesta del paciente, incidentes, indicaciones y plan de seguimiento. Documentar únicamente lo que realmente se efectuó.","Record date, reason, tooth/site, pre-procedure findings, related diagnosis, resina clase i procedure performed according to the teaching protocol, materials or anesthesia when applicable, patient response, incidents, instructions and follow-up. Document only what was actually performed."),
    NoteTemplate("Resina Clase II","Resina Clase II","Registrar fecha, motivo, OD o zona, hallazgos previos, diagnóstico relacionado, procedimiento de resina clase ii realizado conforme al protocolo docente, materiales o anestesia cuando aplique, respuesta del paciente, incidentes, indicaciones y plan de seguimiento. Documentar únicamente lo que realmente se efectuó.","Record date, reason, tooth/site, pre-procedure findings, related diagnosis, resina clase ii procedure performed according to the teaching protocol, materials or anesthesia when applicable, patient response, incidents, instructions and follow-up. Document only what was actually performed."),
    NoteTemplate("Resina Clase III","Resina Clase III","Registrar fecha, motivo, OD o zona, hallazgos previos, diagnóstico relacionado, procedimiento de resina clase iii realizado conforme al protocolo docente, materiales o anestesia cuando aplique, respuesta del paciente, incidentes, indicaciones y plan de seguimiento. Documentar únicamente lo que realmente se efectuó.","Record date, reason, tooth/site, pre-procedure findings, related diagnosis, resina clase iii procedure performed according to the teaching protocol, materials or anesthesia when applicable, patient response, incidents, instructions and follow-up. Document only what was actually performed."),
    NoteTemplate("Resina Clase IV","Resina Clase IV","Registrar fecha, motivo, OD o zona, hallazgos previos, diagnóstico relacionado, procedimiento de resina clase iv realizado conforme al protocolo docente, materiales o anestesia cuando aplique, respuesta del paciente, incidentes, indicaciones y plan de seguimiento. Documentar únicamente lo que realmente se efectuó.","Record date, reason, tooth/site, pre-procedure findings, related diagnosis, resina clase iv procedure performed according to the teaching protocol, materials or anesthesia when applicable, patient response, incidents, instructions and follow-up. Document only what was actually performed."),
    NoteTemplate("Resina Clase V","Resina Clase V","Registrar fecha, motivo, OD o zona, hallazgos previos, diagnóstico relacionado, procedimiento de resina clase v realizado conforme al protocolo docente, materiales o anestesia cuando aplique, respuesta del paciente, incidentes, indicaciones y plan de seguimiento. Documentar únicamente lo que realmente se efectuó.","Record date, reason, tooth/site, pre-procedure findings, related diagnosis, resina clase v procedure performed according to the teaching protocol, materials or anesthesia when applicable, patient response, incidents, instructions and follow-up. Document only what was actually performed."),
    NoteTemplate("Restauración temporal","Restauración temporal","Registrar fecha, motivo, OD o zona, hallazgos previos, diagnóstico relacionado, procedimiento de restauración temporal realizado conforme al protocolo docente, materiales o anestesia cuando aplique, respuesta del paciente, incidentes, indicaciones y plan de seguimiento. Documentar únicamente lo que realmente se efectuó.","Record date, reason, tooth/site, pre-procedure findings, related diagnosis, restauración temporal procedure performed according to the teaching protocol, materials or anesthesia when applicable, patient response, incidents, instructions and follow-up. Document only what was actually performed."),
    NoteTemplate("Recubrimiento pulpar indirecto","Recubrimiento pulpar indirecto","Registrar fecha, motivo, OD o zona, hallazgos previos, diagnóstico relacionado, procedimiento de recubrimiento pulpar indirecto realizado conforme al protocolo docente, materiales o anestesia cuando aplique, respuesta del paciente, incidentes, indicaciones y plan de seguimiento. Documentar únicamente lo que realmente se efectuó.","Record date, reason, tooth/site, pre-procedure findings, related diagnosis, recubrimiento pulpar indirecto procedure performed according to the teaching protocol, materials or anesthesia when applicable, patient response, incidents, instructions and follow-up. Document only what was actually performed."),
    NoteTemplate("Recubrimiento pulpar directo","Recubrimiento pulpar directo","Registrar fecha, motivo, OD o zona, hallazgos previos, diagnóstico relacionado, procedimiento de recubrimiento pulpar directo realizado conforme al protocolo docente, materiales o anestesia cuando aplique, respuesta del paciente, incidentes, indicaciones y plan de seguimiento. Documentar únicamente lo que realmente se efectuó.","Record date, reason, tooth/site, pre-procedure findings, related diagnosis, recubrimiento pulpar directo procedure performed according to the teaching protocol, materials or anesthesia when applicable, patient response, incidents, instructions and follow-up. Document only what was actually performed."),
    NoteTemplate("Cementación provisional","Cementación provisional","Registrar fecha, motivo, OD o zona, hallazgos previos, diagnóstico relacionado, procedimiento de cementación provisional realizado conforme al protocolo docente, materiales o anestesia cuando aplique, respuesta del paciente, incidentes, indicaciones y plan de seguimiento. Documentar únicamente lo que realmente se efectuó.","Record date, reason, tooth/site, pre-procedure findings, related diagnosis, cementación provisional procedure performed according to the teaching protocol, materials or anesthesia when applicable, patient response, incidents, instructions and follow-up. Document only what was actually performed."),
    NoteTemplate("Cementación definitiva","Cementación definitiva","Registrar fecha, motivo, OD o zona, hallazgos previos, diagnóstico relacionado, procedimiento de cementación definitiva realizado conforme al protocolo docente, materiales o anestesia cuando aplique, respuesta del paciente, incidentes, indicaciones y plan de seguimiento. Documentar únicamente lo que realmente se efectuó.","Record date, reason, tooth/site, pre-procedure findings, related diagnosis, cementación definitiva procedure performed according to the teaching protocol, materials or anesthesia when applicable, patient response, incidents, instructions and follow-up. Document only what was actually performed."),
    NoteTemplate("Toma de impresión con alginato","Toma de impresión con alginato","Registrar fecha, motivo, OD o zona, hallazgos previos, diagnóstico relacionado, procedimiento de toma de impresión con alginato realizado conforme al protocolo docente, materiales o anestesia cuando aplique, respuesta del paciente, incidentes, indicaciones y plan de seguimiento. Documentar únicamente lo que realmente se efectuó.","Record date, reason, tooth/site, pre-procedure findings, related diagnosis, toma de impresión con alginato procedure performed according to the teaching protocol, materials or anesthesia when applicable, patient response, incidents, instructions and follow-up. Document only what was actually performed."),
    NoteTemplate("Vaciado de modelo de estudio","Vaciado de modelo de estudio","Registrar fecha, motivo, OD o zona, hallazgos previos, diagnóstico relacionado, procedimiento de vaciado de modelo de estudio realizado conforme al protocolo docente, materiales o anestesia cuando aplique, respuesta del paciente, incidentes, indicaciones y plan de seguimiento. Documentar únicamente lo que realmente se efectuó.","Record date, reason, tooth/site, pre-procedure findings, related diagnosis, vaciado de modelo de estudio procedure performed according to the teaching protocol, materials or anesthesia when applicable, patient response, incidents, instructions and follow-up. Document only what was actually performed."),
    NoteTemplate("Registro intermaxilar","Registro intermaxilar","Registrar fecha, motivo, OD o zona, hallazgos previos, diagnóstico relacionado, procedimiento de registro intermaxilar realizado conforme al protocolo docente, materiales o anestesia cuando aplique, respuesta del paciente, incidentes, indicaciones y plan de seguimiento. Documentar únicamente lo que realmente se efectuó.","Record date, reason, tooth/site, pre-procedure findings, related diagnosis, registro intermaxilar procedure performed according to the teaching protocol, materials or anesthesia when applicable, patient response, incidents, instructions and follow-up. Document only what was actually performed."),
    NoteTemplate("Prueba de prótesis removible","Prueba de prótesis removible","Registrar fecha, motivo, OD o zona, hallazgos previos, diagnóstico relacionado, procedimiento de prueba de prótesis removible realizado conforme al protocolo docente, materiales o anestesia cuando aplique, respuesta del paciente, incidentes, indicaciones y plan de seguimiento. Documentar únicamente lo que realmente se efectuó.","Record date, reason, tooth/site, pre-procedure findings, related diagnosis, prueba de prótesis removible procedure performed according to the teaching protocol, materials or anesthesia when applicable, patient response, incidents, instructions and follow-up. Document only what was actually performed."),
    NoteTemplate("Entrega de prótesis removible","Entrega de prótesis removible","Registrar fecha, motivo, OD o zona, hallazgos previos, diagnóstico relacionado, procedimiento de entrega de prótesis removible realizado conforme al protocolo docente, materiales o anestesia cuando aplique, respuesta del paciente, incidentes, indicaciones y plan de seguimiento. Documentar únicamente lo que realmente se efectuó.","Record date, reason, tooth/site, pre-procedure findings, related diagnosis, entrega de prótesis removible procedure performed according to the teaching protocol, materials or anesthesia when applicable, patient response, incidents, instructions and follow-up. Document only what was actually performed."),
    NoteTemplate("Ajuste de prótesis removible","Ajuste de prótesis removible","Registrar fecha, motivo, OD o zona, hallazgos previos, diagnóstico relacionado, procedimiento de ajuste de prótesis removible realizado conforme al protocolo docente, materiales o anestesia cuando aplique, respuesta del paciente, incidentes, indicaciones y plan de seguimiento. Documentar únicamente lo que realmente se efectuó.","Record date, reason, tooth/site, pre-procedure findings, related diagnosis, ajuste de prótesis removible procedure performed according to the teaching protocol, materials or anesthesia when applicable, patient response, incidents, instructions and follow-up. Document only what was actually performed."),
    NoteTemplate("Prótesis total · impresión primaria","Prótesis total · impresión primaria","Registrar fecha, motivo, OD o zona, hallazgos previos, diagnóstico relacionado, procedimiento de prótesis total · impresión primaria realizado conforme al protocolo docente, materiales o anestesia cuando aplique, respuesta del paciente, incidentes, indicaciones y plan de seguimiento. Documentar únicamente lo que realmente se efectuó.","Record date, reason, tooth/site, pre-procedure findings, related diagnosis, prótesis total · impresión primaria procedure performed according to the teaching protocol, materials or anesthesia when applicable, patient response, incidents, instructions and follow-up. Document only what was actually performed."),
    NoteTemplate("Prótesis total · impresión definitiva","Prótesis total · impresión definitiva","Registrar fecha, motivo, OD o zona, hallazgos previos, diagnóstico relacionado, procedimiento de prótesis total · impresión definitiva realizado conforme al protocolo docente, materiales o anestesia cuando aplique, respuesta del paciente, incidentes, indicaciones y plan de seguimiento. Documentar únicamente lo que realmente se efectuó.","Record date, reason, tooth/site, pre-procedure findings, related diagnosis, prótesis total · impresión definitiva procedure performed according to the teaching protocol, materials or anesthesia when applicable, patient response, incidents, instructions and follow-up. Document only what was actually performed."),
    NoteTemplate("Prótesis total · relaciones maxilomandibulares","Prótesis total · relaciones maxilomandibulares","Registrar fecha, motivo, OD o zona, hallazgos previos, diagnóstico relacionado, procedimiento de prótesis total · relaciones maxilomandibulares realizado conforme al protocolo docente, materiales o anestesia cuando aplique, respuesta del paciente, incidentes, indicaciones y plan de seguimiento. Documentar únicamente lo que realmente se efectuó.","Record date, reason, tooth/site, pre-procedure findings, related diagnosis, prótesis total · relaciones maxilomandibulares procedure performed according to the teaching protocol, materials or anesthesia when applicable, patient response, incidents, instructions and follow-up. Document only what was actually performed."),
    NoteTemplate("Prótesis total · prueba de dientes","Prótesis total · prueba de dientes","Registrar fecha, motivo, OD o zona, hallazgos previos, diagnóstico relacionado, procedimiento de prótesis total · prueba de dientes realizado conforme al protocolo docente, materiales o anestesia cuando aplique, respuesta del paciente, incidentes, indicaciones y plan de seguimiento. Documentar únicamente lo que realmente se efectuó.","Record date, reason, tooth/site, pre-procedure findings, related diagnosis, prótesis total · prueba de dientes procedure performed according to the teaching protocol, materials or anesthesia when applicable, patient response, incidents, instructions and follow-up. Document only what was actually performed."),
    NoteTemplate("Prótesis total · entrega","Prótesis total · entrega","Registrar fecha, motivo, OD o zona, hallazgos previos, diagnóstico relacionado, procedimiento de prótesis total · entrega realizado conforme al protocolo docente, materiales o anestesia cuando aplique, respuesta del paciente, incidentes, indicaciones y plan de seguimiento. Documentar únicamente lo que realmente se efectuó.","Record date, reason, tooth/site, pre-procedure findings, related diagnosis, prótesis total · entrega procedure performed according to the teaching protocol, materials or anesthesia when applicable, patient response, incidents, instructions and follow-up. Document only what was actually performed."),
    NoteTemplate("Preparación para corona","Preparación para corona","Registrar fecha, motivo, OD o zona, hallazgos previos, diagnóstico relacionado, procedimiento de preparación para corona realizado conforme al protocolo docente, materiales o anestesia cuando aplique, respuesta del paciente, incidentes, indicaciones y plan de seguimiento. Documentar únicamente lo que realmente se efectuó.","Record date, reason, tooth/site, pre-procedure findings, related diagnosis, preparación para corona procedure performed according to the teaching protocol, materials or anesthesia when applicable, patient response, incidents, instructions and follow-up. Document only what was actually performed."),
    NoteTemplate("Impresión para prótesis fija","Impresión para prótesis fija","Registrar fecha, motivo, OD o zona, hallazgos previos, diagnóstico relacionado, procedimiento de impresión para prótesis fija realizado conforme al protocolo docente, materiales o anestesia cuando aplique, respuesta del paciente, incidentes, indicaciones y plan de seguimiento. Documentar únicamente lo que realmente se efectuó.","Record date, reason, tooth/site, pre-procedure findings, related diagnosis, impresión para prótesis fija procedure performed according to the teaching protocol, materials or anesthesia when applicable, patient response, incidents, instructions and follow-up. Document only what was actually performed."),
    NoteTemplate("Prueba de estructura protésica","Prueba de estructura protésica","Registrar fecha, motivo, OD o zona, hallazgos previos, diagnóstico relacionado, procedimiento de prueba de estructura protésica realizado conforme al protocolo docente, materiales o anestesia cuando aplique, respuesta del paciente, incidentes, indicaciones y plan de seguimiento. Documentar únicamente lo que realmente se efectuó.","Record date, reason, tooth/site, pre-procedure findings, related diagnosis, prueba de estructura protésica procedure performed according to the teaching protocol, materials or anesthesia when applicable, patient response, incidents, instructions and follow-up. Document only what was actually performed."),
    NoteTemplate("Prueba de corona","Prueba de corona","Registrar fecha, motivo, OD o zona, hallazgos previos, diagnóstico relacionado, procedimiento de prueba de corona realizado conforme al protocolo docente, materiales o anestesia cuando aplique, respuesta del paciente, incidentes, indicaciones y plan de seguimiento. Documentar únicamente lo que realmente se efectuó.","Record date, reason, tooth/site, pre-procedure findings, related diagnosis, prueba de corona procedure performed according to the teaching protocol, materials or anesthesia when applicable, patient response, incidents, instructions and follow-up. Document only what was actually performed."),
    NoteTemplate("Raspado y alisado radicular","Raspado y alisado radicular","Registrar fecha, motivo, OD o zona, hallazgos previos, diagnóstico relacionado, procedimiento de raspado y alisado radicular realizado conforme al protocolo docente, materiales o anestesia cuando aplique, respuesta del paciente, incidentes, indicaciones y plan de seguimiento. Documentar únicamente lo que realmente se efectuó.","Record date, reason, tooth/site, pre-procedure findings, related diagnosis, raspado y alisado radicular procedure performed according to the teaching protocol, materials or anesthesia when applicable, patient response, incidents, instructions and follow-up. Document only what was actually performed."),
    NoteTemplate("Sondaje periodontal","Sondaje periodontal","Registrar fecha, motivo, OD o zona, hallazgos previos, diagnóstico relacionado, procedimiento de sondaje periodontal realizado conforme al protocolo docente, materiales o anestesia cuando aplique, respuesta del paciente, incidentes, indicaciones y plan de seguimiento. Documentar únicamente lo que realmente se efectuó.","Record date, reason, tooth/site, pre-procedure findings, related diagnosis, sondaje periodontal procedure performed according to the teaching protocol, materials or anesthesia when applicable, patient response, incidents, instructions and follow-up. Document only what was actually performed."),
    NoteTemplate("Reevaluación periodontal","Reevaluación periodontal","Registrar fecha, motivo, OD o zona, hallazgos previos, diagnóstico relacionado, procedimiento de reevaluación periodontal realizado conforme al protocolo docente, materiales o anestesia cuando aplique, respuesta del paciente, incidentes, indicaciones y plan de seguimiento. Documentar únicamente lo que realmente se efectuó.","Record date, reason, tooth/site, pre-procedure findings, related diagnosis, reevaluación periodontal procedure performed according to the teaching protocol, materials or anesthesia when applicable, patient response, incidents, instructions and follow-up. Document only what was actually performed."),
    NoteTemplate("Gingivectomía académica","Gingivectomía académica","Registrar fecha, motivo, OD o zona, hallazgos previos, diagnóstico relacionado, procedimiento de gingivectomía académica realizado conforme al protocolo docente, materiales o anestesia cuando aplique, respuesta del paciente, incidentes, indicaciones y plan de seguimiento. Documentar únicamente lo que realmente se efectuó.","Record date, reason, tooth/site, pre-procedure findings, related diagnosis, gingivectomía académica procedure performed according to the teaching protocol, materials or anesthesia when applicable, patient response, incidents, instructions and follow-up. Document only what was actually performed."),
    NoteTemplate("Ferulización periodontal","Ferulización periodontal","Registrar fecha, motivo, OD o zona, hallazgos previos, diagnóstico relacionado, procedimiento de ferulización periodontal realizado conforme al protocolo docente, materiales o anestesia cuando aplique, respuesta del paciente, incidentes, indicaciones y plan de seguimiento. Documentar únicamente lo que realmente se efectuó.","Record date, reason, tooth/site, pre-procedure findings, related diagnosis, ferulización periodontal procedure performed according to the teaching protocol, materials or anesthesia when applicable, patient response, incidents, instructions and follow-up. Document only what was actually performed."),
    NoteTemplate("Anestesia local infiltrativa","Anestesia local infiltrativa","Registrar fecha, motivo, OD o zona, hallazgos previos, diagnóstico relacionado, procedimiento de anestesia local infiltrativa realizado conforme al protocolo docente, materiales o anestesia cuando aplique, respuesta del paciente, incidentes, indicaciones y plan de seguimiento. Documentar únicamente lo que realmente se efectuó.","Record date, reason, tooth/site, pre-procedure findings, related diagnosis, anestesia local infiltrativa procedure performed according to the teaching protocol, materials or anesthesia when applicable, patient response, incidents, instructions and follow-up. Document only what was actually performed."),
    NoteTemplate("Bloqueo regional","Bloqueo regional","Registrar fecha, motivo, OD o zona, hallazgos previos, diagnóstico relacionado, procedimiento de bloqueo regional realizado conforme al protocolo docente, materiales o anestesia cuando aplique, respuesta del paciente, incidentes, indicaciones y plan de seguimiento. Documentar únicamente lo que realmente se efectuó.","Record date, reason, tooth/site, pre-procedure findings, related diagnosis, bloqueo regional procedure performed according to the teaching protocol, materials or anesthesia when applicable, patient response, incidents, instructions and follow-up. Document only what was actually performed."),
    NoteTemplate("Aislamiento absoluto","Aislamiento absoluto","Registrar fecha, motivo, OD o zona, hallazgos previos, diagnóstico relacionado, procedimiento de aislamiento absoluto realizado conforme al protocolo docente, materiales o anestesia cuando aplique, respuesta del paciente, incidentes, indicaciones y plan de seguimiento. Documentar únicamente lo que realmente se efectuó.","Record date, reason, tooth/site, pre-procedure findings, related diagnosis, aislamiento absoluto procedure performed according to the teaching protocol, materials or anesthesia when applicable, patient response, incidents, instructions and follow-up. Document only what was actually performed."),
    NoteTemplate("Aislamiento relativo","Aislamiento relativo","Registrar fecha, motivo, OD o zona, hallazgos previos, diagnóstico relacionado, procedimiento de aislamiento relativo realizado conforme al protocolo docente, materiales o anestesia cuando aplique, respuesta del paciente, incidentes, indicaciones y plan de seguimiento. Documentar únicamente lo que realmente se efectuó.","Record date, reason, tooth/site, pre-procedure findings, related diagnosis, aislamiento relativo procedure performed according to the teaching protocol, materials or anesthesia when applicable, patient response, incidents, instructions and follow-up. Document only what was actually performed."),
    NoteTemplate("Urgencia por dolor dental","Urgencia por dolor dental","Registrar fecha, motivo, OD o zona, hallazgos previos, diagnóstico relacionado, procedimiento de urgencia por dolor dental realizado conforme al protocolo docente, materiales o anestesia cuando aplique, respuesta del paciente, incidentes, indicaciones y plan de seguimiento. Documentar únicamente lo que realmente se efectuó.","Record date, reason, tooth/site, pre-procedure findings, related diagnosis, urgencia por dolor dental procedure performed according to the teaching protocol, materials or anesthesia when applicable, patient response, incidents, instructions and follow-up. Document only what was actually performed."),
    NoteTemplate("Manejo de alveolitis","Manejo de alveolitis","Registrar fecha, motivo, OD o zona, hallazgos previos, diagnóstico relacionado, procedimiento de manejo de alveolitis realizado conforme al protocolo docente, materiales o anestesia cuando aplique, respuesta del paciente, incidentes, indicaciones y plan de seguimiento. Documentar únicamente lo que realmente se efectuó.","Record date, reason, tooth/site, pre-procedure findings, related diagnosis, manejo de alveolitis procedure performed according to the teaching protocol, materials or anesthesia when applicable, patient response, incidents, instructions and follow-up. Document only what was actually performed."),
    NoteTemplate("Retiro de suturas","Retiro de suturas","Registrar fecha, motivo, OD o zona, hallazgos previos, diagnóstico relacionado, procedimiento de retiro de suturas realizado conforme al protocolo docente, materiales o anestesia cuando aplique, respuesta del paciente, incidentes, indicaciones y plan de seguimiento. Documentar únicamente lo que realmente se efectuó.","Record date, reason, tooth/site, pre-procedure findings, related diagnosis, retiro de suturas procedure performed according to the teaching protocol, materials or anesthesia when applicable, patient response, incidents, instructions and follow-up. Document only what was actually performed."),
    NoteTemplate("Control postextracción","Control postextracción","Registrar fecha, motivo, OD o zona, hallazgos previos, diagnóstico relacionado, procedimiento de control postextracción realizado conforme al protocolo docente, materiales o anestesia cuando aplique, respuesta del paciente, incidentes, indicaciones y plan de seguimiento. Documentar únicamente lo que realmente se efectuó.","Record date, reason, tooth/site, pre-procedure findings, related diagnosis, control postextracción procedure performed according to the teaching protocol, materials or anesthesia when applicable, patient response, incidents, instructions and follow-up. Document only what was actually performed."),
    NoteTemplate("Biopsia incisional","Biopsia incisional","Registrar fecha, motivo, OD o zona, hallazgos previos, diagnóstico relacionado, procedimiento de biopsia incisional realizado conforme al protocolo docente, materiales o anestesia cuando aplique, respuesta del paciente, incidentes, indicaciones y plan de seguimiento. Documentar únicamente lo que realmente se efectuó.","Record date, reason, tooth/site, pre-procedure findings, related diagnosis, biopsia incisional procedure performed according to the teaching protocol, materials or anesthesia when applicable, patient response, incidents, instructions and follow-up. Document only what was actually performed."),
    NoteTemplate("Biopsia excisional","Biopsia excisional","Registrar fecha, motivo, OD o zona, hallazgos previos, diagnóstico relacionado, procedimiento de biopsia excisional realizado conforme al protocolo docente, materiales o anestesia cuando aplique, respuesta del paciente, incidentes, indicaciones y plan de seguimiento. Documentar únicamente lo que realmente se efectuó.","Record date, reason, tooth/site, pre-procedure findings, related diagnosis, biopsia excisional procedure performed according to the teaching protocol, materials or anesthesia when applicable, patient response, incidents, instructions and follow-up. Document only what was actually performed."),
    NoteTemplate("Toma de muestra microbiológica","Toma de muestra microbiológica","Registrar fecha, motivo, OD o zona, hallazgos previos, diagnóstico relacionado, procedimiento de toma de muestra microbiológica realizado conforme al protocolo docente, materiales o anestesia cuando aplique, respuesta del paciente, incidentes, indicaciones y plan de seguimiento. Documentar únicamente lo que realmente se efectuó.","Record date, reason, tooth/site, pre-procedure findings, related diagnosis, toma de muestra microbiológica procedure performed according to the teaching protocol, materials or anesthesia when applicable, patient response, incidents, instructions and follow-up. Document only what was actually performed."),
    NoteTemplate("Radiografía periapical","Radiografía periapical","Registrar fecha, motivo, OD o zona, hallazgos previos, diagnóstico relacionado, procedimiento de radiografía periapical realizado conforme al protocolo docente, materiales o anestesia cuando aplique, respuesta del paciente, incidentes, indicaciones y plan de seguimiento. Documentar únicamente lo que realmente se efectuó.","Record date, reason, tooth/site, pre-procedure findings, related diagnosis, radiografía periapical procedure performed according to the teaching protocol, materials or anesthesia when applicable, patient response, incidents, instructions and follow-up. Document only what was actually performed."),
    NoteTemplate("Radiografía aleta mordible","Radiografía aleta mordible","Registrar fecha, motivo, OD o zona, hallazgos previos, diagnóstico relacionado, procedimiento de radiografía aleta mordible realizado conforme al protocolo docente, materiales o anestesia cuando aplique, respuesta del paciente, incidentes, indicaciones y plan de seguimiento. Documentar únicamente lo que realmente se efectuó.","Record date, reason, tooth/site, pre-procedure findings, related diagnosis, radiografía aleta mordible procedure performed according to the teaching protocol, materials or anesthesia when applicable, patient response, incidents, instructions and follow-up. Document only what was actually performed."),
    NoteTemplate("Radiografía oclusal","Radiografía oclusal","Registrar fecha, motivo, OD o zona, hallazgos previos, diagnóstico relacionado, procedimiento de radiografía oclusal realizado conforme al protocolo docente, materiales o anestesia cuando aplique, respuesta del paciente, incidentes, indicaciones y plan de seguimiento. Documentar únicamente lo que realmente se efectuó.","Record date, reason, tooth/site, pre-procedure findings, related diagnosis, radiografía oclusal procedure performed according to the teaching protocol, materials or anesthesia when applicable, patient response, incidents, instructions and follow-up. Document only what was actually performed."),
    NoteTemplate("Radiografía panorámica","Radiografía panorámica","Registrar fecha, motivo, OD o zona, hallazgos previos, diagnóstico relacionado, procedimiento de radiografía panorámica realizado conforme al protocolo docente, materiales o anestesia cuando aplique, respuesta del paciente, incidentes, indicaciones y plan de seguimiento. Documentar únicamente lo que realmente se efectuó.","Record date, reason, tooth/site, pre-procedure findings, related diagnosis, radiografía panorámica procedure performed according to the teaching protocol, materials or anesthesia when applicable, patient response, incidents, instructions and follow-up. Document only what was actually performed."),
    NoteTemplate("Cefalometría básica de Steiner","Cefalometría básica de Steiner","Registrar fecha, motivo, OD o zona, hallazgos previos, diagnóstico relacionado, procedimiento de cefalometría básica de steiner realizado conforme al protocolo docente, materiales o anestesia cuando aplique, respuesta del paciente, incidentes, indicaciones y plan de seguimiento. Documentar únicamente lo que realmente se efectuó.","Record date, reason, tooth/site, pre-procedure findings, related diagnosis, cefalometría básica de steiner procedure performed according to the teaching protocol, materials or anesthesia when applicable, patient response, incidents, instructions and follow-up. Document only what was actually performed."),
    NoteTemplate("Fotografía clínica y análisis facial","Fotografía clínica y análisis facial","Registrar fecha, motivo, OD o zona, hallazgos previos, diagnóstico relacionado, procedimiento de fotografía clínica y análisis facial realizado conforme al protocolo docente, materiales o anestesia cuando aplique, respuesta del paciente, incidentes, indicaciones y plan de seguimiento. Documentar únicamente lo que realmente se efectuó.","Record date, reason, tooth/site, pre-procedure findings, related diagnosis, fotografía clínica y análisis facial procedure performed according to the teaching protocol, materials or anesthesia when applicable, patient response, incidents, instructions and follow-up. Document only what was actually performed."),
    NoteTemplate("Alta preventiva","Alta preventiva","Registrar fecha, motivo, OD o zona, hallazgos previos, diagnóstico relacionado, procedimiento de alta preventiva realizado conforme al protocolo docente, materiales o anestesia cuando aplique, respuesta del paciente, incidentes, indicaciones y plan de seguimiento. Documentar únicamente lo que realmente se efectuó.","Record date, reason, tooth/site, pre-procedure findings, related diagnosis, alta preventiva procedure performed according to the teaching protocol, materials or anesthesia when applicable, patient response, incidents, instructions and follow-up. Document only what was actually performed.")
)

@Composable
fun EvolutionScreen(lang: String, session: EducationalSession, onBack: () -> Unit) {
    var selected by remember { mutableStateOf(0) }
    var site by remember { mutableStateOf("OD / zona seleccionada") }
    var status by remember { mutableStateOf("Paciente estable y cooperador") }
    var anesthesia by remember { mutableStateOf("No requerida") }
    var incidents by remember { mutableStateOf("Sin incidentes") }
    var instructions by remember { mutableStateOf("Indicaciones generales y signos de alarma") }
    var followUp by remember { mutableStateOf("Control programado") }
    var supervision by remember { mutableStateOf("Realizado bajo supervisión docente") }
    val newTreatments=listOf(
        NoteTemplate("Toma de impresiones diagnósticas","Diagnostic impressions","Registrar indicación, arcada, material de impresión, selección de cubeta, calidad de la impresión, desinfección/manejo conforme al protocolo y destino para modelo de estudio.","Record indication, arch, impression material, tray selection, impression quality, disinfection/handling per protocol and destination for study cast."),
        NoteTemplate("Análisis de modelos","Model analysis","Registrar modelos analizados, dentición, mediciones efectuadas, discrepancias de espacio y hallazgos relevantes; documentar el método empleado.","Record casts analyzed, dentition, measurements, space discrepancies and relevant findings; document the method used."),
        NoteTemplate("Análisis radiográfico","Radiographic analysis","Registrar tipo de estudio, fecha, calidad diagnóstica, estructuras evaluadas, hallazgos y correlación clínica; no emitir conclusiones fuera del alcance del estudio.","Record imaging type, date, diagnostic quality, evaluated structures, findings and clinical correlation."),
        NoteTemplate("Análisis fotográfico","Photographic analysis","Registrar vistas obtenidas, estandarización disponible, hallazgos faciales/intraorales y correlación con la exploración clínica.","Record views obtained, available standardization, facial/intraoral findings and clinical correlation."),
        NoteTemplate("Análisis cefalométrico de Steiner","Steiner cephalometric analysis","Registrar trazado y puntos utilizados, SNA, SNB, ANB y GoGn-SN, calidad del estudio e interpretación dentro del contexto clínico.","Record tracing/landmarks, SNA, SNB, ANB and GoGn-SN, study quality and interpretation in clinical context."),
        NoteTemplate("CAMBRA · riesgo de caries","CAMBRA caries risk","Registrar factores de enfermedad, riesgo y protección seleccionados, categoría obtenida y plan preventivo individualizado; reevaluar según evolución.","Record selected disease, risk and protective factors, resulting category and individualized preventive plan; reassess over time."),
        NoteTemplate("Índice de placa O’Leary","O’Leary plaque index","Registrar superficies reveladas/evaluadas, superficies con placa, cálculo del porcentaje e instrucciones de higiene derivadas del hallazgo.","Record disclosed/evaluated surfaces, plaque-positive surfaces, percentage calculation and hygiene instruction based on findings."),
        NoteTemplate("CPO-D / ceo-d","DMFT / dmft","Registrar dentición evaluada y componentes cariados, perdidos por caries y obturados conforme al índice utilizado, además del resultado calculado.","Record evaluated dentition and decayed, missing due to caries and filled components according to the selected index, plus calculated result."),
        NoteTemplate("ICDAS","ICDAS","Registrar superficies limpias y evaluables, código seleccionado por superficie y condiciones de examen; correlacionar con actividad/riesgo antes del plan.","Record clean/evaluable surfaces, selected surface code and examination conditions; correlate with activity/risk before planning."),
        NoteTemplate("IPC","CPI","Registrar sextantes evaluables, hallazgos/códigos obtenidos y necesidad de completar valoración periodontal cuando corresponda.","Record assessable sextants, findings/codes and need for complete periodontal assessment when indicated."),
        NoteTemplate("IHOS","OHI-S","Registrar dientes/superficies índice evaluadas, depósitos blandos y cálculo conforme al índice, resultado y orientación de higiene.","Record index teeth/surfaces, debris and calculus according to the index, result and hygiene guidance."),
        NoteTemplate("Exploración de mucosas","Oral mucosa examination","Registrar sitios examinados, aspecto de mucosas, lesiones o ausencia de ellas, localización, características y conducta de seguimiento/remisión cuando proceda.","Record examined sites, mucosal appearance, lesions or absence, location, characteristics and follow-up/referral when indicated."),
        NoteTemplate("Mantenedor banda y ansa","Band-and-loop space maintainer","Registrar indicación por pérdida prematura, diente/espacio, evaluación clínica y radiográfica, adaptación, cementación, oclusión, higiene y control.","Record indication after premature loss, tooth/space, clinical/radiographic assessment, fit, cementation, occlusion, hygiene and follow-up."),
        NoteTemplate("Mantenedor corona y ansa","Crown-and-loop space maintainer","Registrar indicación, diente pilar, restauración/corona, ansa, adaptación, cementación, oclusión y seguimiento de erupción.","Record indication, abutment tooth, crown/restoration, loop, fit, cementation, occlusion and eruption follow-up."),
        NoteTemplate("Arco lingual como mantenedor","Lingual arch space maintainer","Registrar indicación, dentición, dientes pilares, adaptación del arco, cementación, oclusión, tejidos y controles.","Record indication, dentition, abutments, arch fit, cementation, occlusion, tissues and follow-up."),
        NoteTemplate("Botón de Nance","Nance appliance","Registrar indicación, anclaje, adaptación, estado de mucosa palatina, cementación, higiene y controles.","Record indication, anchorage, fit, palatal mucosal status, cementation, hygiene and follow-up."),
        NoteTemplate("Arco transpalatino","Transpalatal arch","Registrar indicación, molares pilares, adaptación, cementación, relación con tejidos, oclusión y seguimiento.","Record indication, molar abutments, fit, cementation, tissue relationship, occlusion and follow-up."),
        NoteTemplate("Zapatilla distal","Distal shoe space maintainer","Registrar indicación y evaluación radiográfica, diente pilar, relación con el sucesor, procedimiento autorizado, control clínico/radiográfico y plan de sustitución cuando corresponda.","Record indication and imaging assessment, abutment, successor relationship, authorized procedure, clinical/radiographic follow-up and replacement plan when applicable."),
        NoteTemplate("Recuperador de espacio","Space regainer","Registrar pérdida de espacio diagnosticada, análisis previo, aparato seleccionado, activación realizada bajo supervisión, respuesta y controles.","Record diagnosed space loss, prior analysis, selected appliance, supervised activation, response and follow-up."),
        NoteTemplate("Extracciones seriadas","Serial extraction","Registrar diagnóstico ortodóncico, análisis de espacio, secuencia indicada y autorizada, pieza intervenida, evolución eruptiva y controles; no registrar como procedimiento aislado sin planificación ortodóncica.","Record orthodontic diagnosis, space analysis, indicated/authorized sequence, treated tooth, eruption progress and follow-up; do not record as an isolated procedure without orthodontic planning."),
        NoteTemplate("Pulpotomía en dentición temporal","Primary-tooth pulpotomy","Registrar diagnóstico pulpar/periapical, restaurabilidad, aislamiento, procedimiento, control de hemorragia, biomaterial, sellado/restauración y seguimiento.","Record pulpal/periapical diagnosis, restorability, isolation, procedure, bleeding control, biomaterial, seal/restoration and follow-up."),
        NoteTemplate("Pulpectomía en dentición temporal","Primary-tooth pulpectomy","Registrar diagnóstico, restaurabilidad, aislamiento, longitud de trabajo según protocolo, preparación/irrigación segura, material obturador apropiado, restauración y seguimiento.","Record diagnosis, restorability, isolation, working length per protocol, safe preparation/irrigation, appropriate filling material, restoration and follow-up."),
        NoteTemplate("Corona de acero cromo en odontopediatría","Pediatric stainless-steel crown","Registrar diente e indicación, preparación, selección y adaptación de corona, cementación, contactos/oclusión, tejidos e indicaciones de control.","Record tooth and indication, preparation, crown selection/fit, cementation, contacts/occlusion, tissues and follow-up instructions."),
        NoteTemplate("Pulpectomía instrumentada en dentición temporal","Instrumented primary-tooth pulpectomy","Registrar diagnóstico, restaurabilidad, aislamiento, conductometría/longitud de trabajo según protocolo, instrumentación, irrigación segura, secado, material obturador, restauración coronal y seguimiento clínico-radiográfico.","Record diagnosis, restorability, isolation, working length per protocol, instrumentation, safe irrigation, drying, filling material, coronal restoration and clinical/radiographic follow-up."),
        NoteTemplate("Terapia pulpar no instrumentada con pasta CTZ","Non-instrumented pulp therapy with CTZ paste","Registrar diagnóstico e indicación docente, diente, hallazgos clínicos/radiográficos, aislamiento, técnica no instrumentada y material CTZ conforme al protocolo institucional, restauración y seguimiento. Identificarla como técnica específica y no como equivalente automático de una pulpectomía convencional.","Record diagnosis and teaching indication, tooth, clinical/imaging findings, isolation, non-instrumented technique and CTZ material per institutional protocol, restoration and follow-up. Identify it as a specific technique, not an automatic equivalent of conventional pulpectomy."),
        NoteTemplate("Recubrimiento pulpar indirecto","Indirect pulp treatment","Registrar diagnóstico pulpar, profundidad de la lesión, ausencia de exposición, remoción selectiva indicada, material protector/sellado, restauración y seguimiento de vitalidad.","Record pulpal diagnosis, lesion depth, absence of exposure, indicated selective removal, protective material/seal, restoration and vitality follow-up."),
        NoteTemplate("Recubrimiento pulpar directo","Direct pulp cap","Registrar diagnóstico, causa/tamaño de la exposición cuando corresponda, control de hemorragia, material biocompatible utilizado, sellado/restauración y seguimiento clínico-radiográfico.","Record diagnosis, exposure cause/size when applicable, bleeding control, biocompatible material, seal/restoration and clinical/radiographic follow-up."),
        NoteTemplate("Diamino fluoruro de plata","Silver diamine fluoride","Registrar lesión/superficie, indicación para control de caries, consentimiento informado sobre efectos esperados como oscurecimiento de lesión cariada, aislamiento/protección, producto aplicado según protocolo y plan de reevaluación.","Record lesion/surface, caries-control indication, informed consent regarding expected effects such as darkening of carious lesion, isolation/protection, product applied per protocol and reassessment plan."),
        NoteTemplate("Infiltración de resina","Resin infiltration","Registrar diente/superficie, diagnóstico y extensión de la lesión no cavitada indicada, aislamiento, acondicionamiento e infiltración según fabricante, acabado y seguimiento.","Record tooth/surface, diagnosis and extent of indicated noncavitated lesion, isolation, conditioning/infiltration per manufacturer, finishing and follow-up."),
        NoteTemplate("Corona estética pediátrica","Pediatric esthetic crown","Registrar diente e indicación, tipo/material de corona estética, preparación, selección/adaptación, cementación o protocolo adhesivo según sistema, contactos/oclusión, tejidos y control.","Record tooth/indication, esthetic crown type/material, preparation, selection/fit, cementation or bonding protocol per system, contacts/occlusion, tissues and follow-up."),
        NoteTemplate("Restauración provisional con Cavit","Temporary restoration with Cavit","Registrar diente, motivo de provisionalización, condición del acceso/cavidad, colocación del material temporal Cavit conforme al fabricante, verificación del sellado/oclusión y fecha o plan para tratamiento definitivo.","Record tooth, reason for temporization, access/cavity condition, Cavit temporary material placement per manufacturer, seal/occlusion check and definitive treatment plan/date.")
    )
    val clinicalSheets=listOf(
        NoteTemplate("Ficha endodóntica","Endodontic clinical sheet","Registrar OD, diagnóstico pulpar y periapical, pruebas pulpares/periapicales realizadas, hallazgos radiográficos, restaurabilidad, conductos, longitud de trabajo cuando corresponda, procedimiento efectuado y plan de seguimiento. Completar únicamente datos realmente obtenidos.","Record tooth, pulpal/periapical diagnosis, performed tests, imaging findings, restorability, canals, working length when applicable, performed procedure and follow-up. Record only actual findings."),
        NoteTemplate("Ficha quirúrgica","Surgical clinical sheet","Registrar diagnóstico e indicación quirúrgica, sitio/OD, antecedentes y riesgos revisados, estudios auxiliares, consentimiento, procedimiento planeado/realizado, anestesia, hallazgos transoperatorios, hemostasia/sutura, incidentes e indicaciones posoperatorias.","Record surgical diagnosis/indication, site/tooth, reviewed history/risks, aids, consent, planned/performed procedure, anesthesia, intraoperative findings, hemostasis/suture, incidents and postoperative instructions."),
        NoteTemplate("Ficha protésica","Prosthodontic clinical sheet","Registrar diagnóstico protésico, dientes presentes/ausentes y pilares cuando corresponda, tejidos de soporte, tipo de rehabilitación, impresiones/registros/pruebas efectuadas, adaptación, oclusión, materiales y fase del tratamiento.","Record prosthodontic diagnosis, present/missing teeth and abutments when applicable, supporting tissues, rehabilitation type, impressions/records/try-ins, fit, occlusion, materials and treatment phase."),
        NoteTemplate("Ficha periodontal","Periodontal clinical sheet","Registrar hallazgos periodontales obtenidos, sondaje y sangrado cuando se hayan medido, movilidad/furcación cuando corresponda, índices y auxiliares utilizados, diagnóstico periodontal documentado, procedimiento realizado y mantenimiento/reevaluación.","Record obtained periodontal findings, probing/bleeding when measured, mobility/furcation when applicable, indices/aids, documented periodontal diagnosis, performed procedure and maintenance/reassessment.")
    )
    val library=noteLibrary()+supplementalNoteLibraryV39()+newTreatments+clinicalSheets
    var specialty by remember { mutableStateOf("Todas") }
    val specialties=linkedMapOf(
        "Todas" to listOf<String>(),
        "Diagnóstico" to listOf("ingreso","radiograf","fotograf","impresiones diagnósticas","modelos","steiner","cambra","o’leary","cpo-d","ceo-d","icdas","ipc","ihos","mucosas","ficha endodóntica","ficha quirúrgica","ficha protésica","ficha periodontal"),
        "Preventiva" to listOf("profilaxis","sellador","flúor","higiene","preventiva"),
        "Operatoria / restauradora" to listOf("resina","amalgama","ionómero","incrustación","onlay","restaur","corona definitiva","corona provisional"),
        "Periodoncia" to listOf("periodon","raspado","destartraje","gingiv"),
        "Endodoncia" to listOf("conductos","endod"),
        "Cirugía" to listOf("exodoncia","extracción","cirugía","sutura","biopsia","alveol"),
        "Prótesis" to listOf("prótesis","impresión para prótesis","intermaxilar","estructura protésica","prueba de dientes","cementación"),
        "Ortodoncia / ortopedia" to listOf("mantenedor","banda y ansa","corona y ansa","arco lingual","nance","transpalatino","zapatilla distal","recuperador de espacio","extracciones seriadas","ortodon","férula","aparato"),
        "Odontopediatría" to listOf("dentición temporal","acero cromo","corona estética pediátrica","pulpotomía","pulpectomía","ctz","recubrimiento pulpar","diamino fluoruro","infiltración de resina","cavit","mantenedor","zapatilla distal"),
        "Administrativa / seguimiento" to listOf("alta","baja","inasistencia","remisión","interconsulta")
    )
    fun matchesSpecialty(x:NoteTemplate):Boolean {
        if(specialty=="Todas") return true
        val hay=(x.titleEs+" "+x.titleEn).lowercase()
        return specialties[specialty].orEmpty().any{hay.contains(it)}
    }
    val visibleLibrary=library.withIndex().filter{matchesSpecialty(it.value)}
    val effectiveSelected = if (visibleLibrary.any { it.index == selected }) selected else visibleLibrary.firstOrNull()?.index ?: 0
    val n=library[effectiveSelected]
    val sites=listOf("OD / zona seleccionada","Cuadrante","Arcada","Mucosa oral","Periodonto","ATM / región craneofacial")
    val states=listOf("Paciente estable y cooperador","Paciente ansioso pero cooperador","Requiere reevaluación antes de continuar","Procedimiento diferido")
    val anesthesias=listOf("No requerida","Anestesia local según protocolo","Anestesia tópica según protocolo","Dato no aplicable")
    val incidentOptions=listOf("Sin incidentes","Sangrado controlado","Dolor durante el procedimiento","Dificultad técnica","Reacción adversa / suspender y valorar")
    val instructionOptions=listOf("Indicaciones generales y signos de alarma","Higiene oral reforzada","Cuidados posoperatorios","Cuidados de restauración / prótesis","Remisión e indicaciones del servicio")
    val followOptions=listOf("Control programado","Continuar tratamiento por fases","Revaloración clínica","Control radiográfico indicado","Remisión a otro servicio","Alta del procedimiento")
    val supervisionOptions=listOf("Realizado bajo supervisión docente","Revisado por docente","Pendiente de revisión docente")
    val procedure=if(lang=="en") n.titleEn else n.titleEs
    val generated=if(lang=="en")
        "$site. $status. Procedure: $procedure. Anesthesia: $anesthesia. Incidents: $incidents. Instructions: $instructions. Follow-up: $followUp. $supervision."
    else "$site. $status. Procedimiento realizado: $procedure. Anestesia: $anesthesia. Incidentes: $incidents. Indicaciones: $instructions. Seguimiento: $followUp. $supervision."

    LazyColumn(Modifier.fillMaxSize().padding(18.dp),verticalArrangement=Arrangement.spacedBy(12.dp)) {
        item { ScreenHeader(tr(lang,"Notas de evolución · generador","Progress notes · generator"),onBack,
            tr(lang,"Selecciona únicamente lo que realmente ocurrió durante la cita. La app construye la redacción clínica sin que el alumno tenga que escribirla.","Select only what actually occurred during the appointment. The app builds the clinical wording without requiring free text.")) }
        item { NoticeCard(tr(lang,"La nota debe corresponder al expediente real: fecha/hora institucional, diagnóstico, procedimiento, materiales y datos clínicos deben verificarse antes de firmar.","The note must match the real record: institutional date/time, diagnosis, procedure, materials and clinical data must be verified before signing.")) }
        item { SectionCard(tr(lang,"1 · Procedimiento realizado","1 · Procedure performed")) {
            Text(tr(lang,"Especialidad / tipo de tratamiento","Specialty / treatment type"),fontWeight=FontWeight.Bold)
            ChipChoices(specialties.keys.map{x->x to (specialty==x)},{i-> specialty=specialties.keys.elementAt(i); selected=0 },columns=3)
            Text(tr(lang,"Tratamiento / actividad","Treatment / activity"),fontWeight=FontWeight.Bold)
            ChipChoices(visibleLibrary.map{(idx,x)->(if(lang=="en")x.titleEn else x.titleEs) to (effectiveSelected==idx)},{i->selected=visibleLibrary[i].index),columns=3)
        }}
        item { SectionCard(tr(lang,"2 · OD o zona","2 · Tooth or site")) { ChipChoices(sites.map{it to (site==it)},{site=sites[it]},columns=4) } }
        item { SectionCard(tr(lang,"3 · Estado durante la cita","3 · Appointment status")) { ChipChoices(states.map{it to (status==it)},{status=states[it]},columns=4) } }
        item { SectionCard(tr(lang,"4 · Anestesia","4 · Anesthesia")) { ChipChoices(anesthesias.map{it to (anesthesia==it)},{anesthesia=anesthesias[it]},columns=4) } }
        item { SectionCard(tr(lang,"5 · Incidentes","5 · Incidents")) { ChipChoices(incidentOptions.map{it to (incidents==it)},{incidents=incidentOptions[it]},columns=4) } }
        item { SectionCard(tr(lang,"6 · Indicaciones","6 · Instructions")) { ChipChoices(instructionOptions.map{it to (instructions==it)},{instructions=instructionOptions[it]},columns=4) } }
        item { SectionCard(tr(lang,"7 · Seguimiento","7 · Follow-up")) { ChipChoices(followOptions.map{it to (followUp==it)},{followUp=followOptions[it]},columns=4) } }
        item { SectionCard(tr(lang,"8 · Supervisión","8 · Supervision")) { ChipChoices(supervisionOptions.map{it to (supervision==it)},{supervision=supervisionOptions[it]},columns=3) } }
        item { SectionCard(tr(lang,"Qué debe llevar esta nota","What this note should contain")) { Text(if(lang=="en")n.textEn else n.textEs) } }
        item { SectionCard(tr(lang,"Ejemplo redactado","Written example")) {
            Text(generated,fontWeight=FontWeight.Bold)
            Text(tr(lang,
                "Ejemplo educativo: Paciente acude a la cita en condiciones estables y cooperador. Se verifica el sitio de trabajo y los antecedentes pertinentes. Se realiza $procedure en $site conforme al diagnóstico y al protocolo clínico autorizado. Anestesia: $anesthesia. Durante el procedimiento: $incidents. Al finalizar se proporcionan $instructions. Se indica $followUp. $supervision. La redacción final debe sustituir estas selecciones por los hallazgos, materiales, dosis y datos que realmente correspondan a la atención realizada.",
                "Educational example: Patient attends the appointment stable and cooperative. The treatment site and relevant history are verified. $procedure is performed at $site according to the diagnosis and authorized clinical protocol. Anesthesia: $anesthesia. During the procedure: $incidents. At completion, $instructions are provided. Plan: $followUp. $supervision. The final note must replace these selections with the actual findings, materials, doses and data from the care provided.")
            )
        } }
        item { NoticeCard(tr(lang,"No debe seleccionarse una opción que no haya ocurrido. Materiales, dosis, técnica, hallazgos y firmas específicas se documentan conforme al formato y protocolo institucional.","Do not select an option that did not occur. Specific materials, doses, technique, findings and signatures are documented according to institutional forms and protocols.")) }
    }
}

