(()=>{
if(typeof S==='undefined'||typeof renderSheet==='undefined') return;
S.protesis={k:'TRATAMIENTO',t:'PRÓTESIS INTERACTIVA',i:'Clasifica el arco, diseña PPR o prótesis fija y revisa protocolos de prótesis total. Cada ruta termina con qué escribir en el expediente.',c:[
 ['Kennedy + Applegate','Marca dientes presentes/ausentes; la web orienta la clase y modificaciones. Kennedy describe la distribución del edentulismo.'],
 ['PDI como complemento','El Prosthodontic Diagnostic Index se incluye como referencia avanzada de complejidad; no sustituye a Kennedy.'],
 ['PPR','Diseña descansos, retenedores, planos guía, base/malla y selecciona material flexible, acrílico o metal-acrílico.'],
 ['Prótesis fija','Marca pilares y pónticos; compara zirconia, metal-cerámica (PFM/PAM/PPM), metálica y disilicato, con esquema de terminación y tipo de póntico.'],
 ['Prótesis total','Secuencia desde diagnóstico e impresiones hasta registros, prueba en cera, inserción y controles.']
]};

const U=[17,16,15,14,13,12,11,21,22,23,24,25,26,27],L=[47,46,45,44,43,42,41,31,32,33,34,35,36,37];
const ps={tab:'diag',up:new Set(U),lo:new Set(L),arch:'up',tool:'restM',material:'metal-acrylic',connector:'AP palatal',fixedMat:'zirconia',pontic:'modified',marksUp:{},marksLo:{}};
function segs(arch,present){let a=[],c=[];arch.forEach(t=>{if(!present.has(t))c.push(t);else if(c.length){a.push(c);c=[]}});if(c.length)a.push(c);return a}
function kennedy(arch,present){if(!present.size)return {c:0,l:'Edéntulo total · Kennedy no aplica',m:0};const s=segs(arch,present);if(!s.length)return{c:0,l:'Sin áreas edéntulas',m:0};let f=arch.findIndex(t=>present.has(t)),la=-1;arch.forEach((t,i)=>{if(present.has(t))la=i});let dr=f>0,dl=la>=0&&la<arch.length-1,mids=arch===U?[11,21]:[41,31],cross=s.some(x=>mids.every(t=>x.includes(t)));let c=dr&&dl?1:(dr||dl?2:(cross&&s.length===1?4:3)),m=c===4?0:Math.max(0,s.length-1),r=['','I','II','III','IV'][c];return{c,l:`Kennedy ${r}${m?` · modificación ${m}`:''}`,m}}
function toothGrid(arch,present,marks,mode){return `<div class="prostho-arch">${arch.map(t=>{let ms=(marks[t]||[]).join(' ');return `<button type="button" class="prostho-tooth ${present.has(t)?'':'missing'} ${ms?'marked':''}" data-tooth="${t}"><span>${present.has(t)?'🦷':'✕'}</span><b>${t}</b><small>${ms}</small></button>`}).join('')}</div>`}
function finishDiagram(mat){let title=mat==='metal'?'Chaflán continuo':mat==='metalceramic'?'Hombro/chaflán según cara':'Hombro redondeado o chaflán profundo';return `<svg class="prostho-diagram" viewBox="0 0 420 150" role="img" aria-label="Esquema de terminación"><rect width="420" height="150" rx="18" fill="#f3e9f8"/><path d="M165 18 L175 105 Q185 122 210 122 Q235 122 245 105 L255 18 Z" fill="#fff" stroke="#43235f" stroke-width="4"/><path d="M90 122 H330" stroke="#62d2c4" stroke-width="7"/><text x="210" y="142" text-anchor="middle" font-size="13" fill="#43235f">${title}</text></svg>`}
function ponticDiagram(type){let d=type==='hygienic'?'M160 28 Q210 5 260 28 L250 88 Q210 78 170 88 Z':type==='ovate'?'M160 28 Q210 5 260 28 L250 82 Q210 140 170 82 Z':type==='conical'?'M160 28 Q210 5 260 28 L245 82 Q210 120 175 82 Z':'M160 28 Q210 5 260 28 L250 82 Q215 116 170 82 Z';return `<svg class="prostho-diagram" viewBox="0 0 420 150" role="img" aria-label="Esquema de póntico"><rect width="420" height="150" rx="18" fill="#edf9f6"/><rect x="70" y="110" width="280" height="25" rx="12" fill="#d4b5df"/><path d="${d}" fill="#fff" stroke="#43235f" stroke-width="4"/><text x="210" y="146" text-anchor="middle" font-size="13" fill="#43235f">Contacto póntico–reborde</text></svg>`}
function materialText(m){return m==='zirconia'?'Zirconia: hombro redondeado o chaflán definido, ángulos internos redondeados y espesor según el sistema/fabricante.':m==='metalceramic'?'Metal-porcelana (PFM/PAM/PPM): hombro redondeado o chaflán profundo en zonas cerámicas; un margen metálico lingual puede usar chaflán más conservador.':m==='metal'?'Metálica: chaflán continuo y conservador, con reducción suficiente para la aleación.':'Disilicato: hombro redondeado o chaflán profundo continuo, sin ángulos internos agudos ni biseles finos; sigue el sistema adhesivo y espesor del fabricante.'}
function markTooth(t){let obj=ps.arch==='up'?ps.marksUp:ps.marksLo,key=String(t),arr=new Set(obj[key]||[]),sym={restM:'M◉',restD:'D◉',cing:'C◉',direct:'⌒',indirect:'◇',guide:'▥',base:'▦',abut:'A',pontic:'P'}[ps.tool];arr.has(sym)?arr.delete(sym):arr.add(sym);obj[key]=[...arr]}
function drawWidget(w){let ku=kennedy(U,ps.up),kl=kennedy(L,ps.lo);let body='';
 if(ps.tab==='diag')body=`<div class="prostho-grid"><div class="prostho-card"><h5>Maxilar</h5>${toothGrid(U,ps.up,{},'presence')}<div class="prostho-result">${ku.l}</div></div><div class="prostho-card"><h5>Mandíbula</h5>${toothGrid(L,ps.lo,{},'presence')}<div class="prostho-result">${kl.l}</div></div></div><div class="prostho-card"><h5>Applegate</h5><p>Clasifica después de extracciones planificadas; el área edéntula más posterior determina la clase; las áreas adicionales son modificaciones; la Clase IV no admite modificaciones. Terceros molares y segundos molares no reemplazados se consideran según su papel real en el plan.</p></div><div class="prostho-write"><b>✍️ ¿Qué escribo al final?</b><br>“Maxilar: ${ku.l}. Mandíbula: ${kl.l}. Áreas edéntulas ___; pilares candidatos ___; pronóstico periodontal/radiográfico ___.”</div>`;
 if(ps.tab==='rpd'){let arch=ps.arch==='up'?U:L,present=ps.arch==='up'?ps.up:ps.lo,marks=ps.arch==='up'?ps.marksUp:ps.marksLo,k=kennedy(arch,present);body=`<div class="prostho-options"><button data-arch="up" class="${ps.arch==='up'?'active':''}">Maxilar</button><button data-arch="lo" class="${ps.arch==='lo'?'active':''}">Mandíbula</button></div><div class="prostho-options"><button data-mat="flexible" class="${ps.material==='flexible'?'active':''}">Flexible</button><button data-mat="acrylic" class="${ps.material==='acrylic'?'active':''}">Acrílica</button><button data-mat="metal-acrylic" class="${ps.material==='metal-acrylic'?'active':''}">Metal-acrílica</button></div><div class="prostho-result">${k.l}</div><div class="prostho-tools">${[['restM','Descanso M'],['restD','Descanso D'],['cing','Cingular'],['direct','Ret. directo'],['indirect','Ret. indirecto'],['guide','Plano guía'],['base','Base/malla']].map(x=>`<button data-tool="${x[0]}" class="${ps.tool===x[0]?'active':''}">${x[1]}</button>`).join('')}</div>${toothGrid(arch,present,marks,'design')}<div class="prostho-legend">M◉ descanso mesial · D◉ distal · C◉ cingular · ⌒ retenedor directo · ◇ indirecto · ▥ plano guía · ▦ base/malla.</div><div class="prostho-card"><h5>Protocolo</h5><p>${k.c===1||k.c===2?'Extensión distal: survey y preparaciones → controlar torque → conector rígido → retención indirecta → impresión de extensión según protocolo → prueba de armazón → registros/prueba en cera → procesado → inserción y controles.':'Dentosoportada: survey → eje de inserción → descansos y planos guía → conector mayor → retenedores/reciprocación → base/malla → impresión → prueba de armazón → registros/prueba en cera → inserción y controles.'}</p></div><div class="prostho-write"><b>✍️ ¿Qué escribo al final?</b><br>PPR ${ps.arch==='up'?'maxilar':'mandibular'}; ${k.l}; base ${ps.material}; descansos ___; retenedores ___; planos guía ___; conector ___; dientes a reemplazar ___.</div>`}
 if(ps.tab==='complete')body=`<div class="prostho-grid"><div class="prostho-card"><h5>Protocolo por etapas</h5><ol><li>Diagnóstico de rebordes, mucosa, saliva, apertura y relación intermaxilar.</li><li>Impresión preliminar y modelo diagnóstico.</li><li>Cubeta individual, modelado periférico e impresión definitiva.</li><li>Bases/rodillos, plano oclusal y dimensión vertical.</li><li>Relación maxilomandibular.</li><li>Selección de dientes y prueba en cera.</li><li>Procesado, inserción y control oclusal.</li><li>Indicaciones y controles.</li></ol></div><div class="prostho-card"><h5>Imagen guía</h5><svg class="prostho-diagram" viewBox="0 0 420 150"><path d="M70 65 Q110 10 210 15 Q310 10 350 65 Q315 95 210 85 Q105 95 70 65Z" fill="#d8b9e6" stroke="#43235f" stroke-width="4"/><path d="M105 112 Q145 145 210 135 Q275 145 315 112 Q275 88 210 100 Q145 88 105 112Z" fill="#bfeee7" stroke="#43235f" stroke-width="4"/></svg><p>Valora soporte, extensión funcional, frenillos, zonas de alivio y relación maxilomandibular.</p></div></div><div class="prostho-write"><b>✍️ ¿Qué escribo al final?</b><br>Edentulismo total ___; condiciones de reborde/mucosa ___; plan ___; etapa realizada ___; ajustes ___; indicaciones y próxima cita ___.</div>`;
 if(ps.tab==='fixed'){let arch=ps.arch==='up'?U:L,present=ps.arch==='up'?ps.up:ps.lo,marks=ps.arch==='up'?ps.marksUp:ps.marksLo;body=`<div class="prostho-options"><button data-arch="up" class="${ps.arch==='up'?'active':''}">Maxilar</button><button data-arch="lo" class="${ps.arch==='lo'?'active':''}">Mandíbula</button></div><div class="prostho-tools"><button data-tool="abut" class="${ps.tool==='abut'?'active':''}">Pilar A</button><button data-tool="pontic" class="${ps.tool==='pontic'?'active':''}">Póntico P</button></div>${toothGrid(arch,present,marks,'design')}<div class="prostho-options">${[['zirconia','Zirconia'],['metalceramic','Metal-porcelana'],['metal','Metálica'],['disilicate','Disilicato']].map(x=>`<button data-fixed="${x[0]}" class="${ps.fixedMat===x[0]?'active':''}">${x[1]}</button>`).join('')}</div>${finishDiagram(ps.fixedMat)}<p class="prostho-note">${materialText(ps.fixedMat)}</p><div class="prostho-options">${[['modified','Silla modificada'],['ovate','Ovoide'],['conical','Cónico'],['hygienic','Higiénico']].map(x=>`<button data-pontic="${x[0]}" class="${ps.pontic===x[0]?'active':''}">${x[1]}</button>`).join('')}</div>${ponticDiagram(ps.pontic)}<div class="prostho-card"><h5>Protocolo fijo</h5><p>Diagnóstico/restaurabilidad → planificación de pilares y tramo → preparación compatible con material → provisional → impresión/escaneo y orden al laboratorio → prueba de ajuste/contactos/oclusión → cementación o adhesión según sistema → controles e higiene.</p></div><div class="prostho-write"><b>✍️ ¿Qué escribo al final?</b><br>Prótesis fija zona ___; pilares ___; pónticos ___; material ${ps.fixedMat}; terminación ___; diseño de póntico ${ps.pontic}; provisional ___; impresión/escaneo ___; cementación/adhesión ___; control ___.</div>`}
 w.querySelector('.prostho-body').innerHTML=body;
 w.querySelectorAll('[data-tab]').forEach(b=>b.onclick=()=>{ps.tab=b.dataset.tab;drawWidget(w)});
 w.querySelectorAll('[data-arch]').forEach(b=>b.onclick=()=>{ps.arch=b.dataset.arch;drawWidget(w)});
 w.querySelectorAll('[data-tool]').forEach(b=>b.onclick=()=>{ps.tool=b.dataset.tool;drawWidget(w)});
 w.querySelectorAll('[data-mat]').forEach(b=>b.onclick=()=>{ps.material=b.dataset.mat;drawWidget(w)});
 w.querySelectorAll('[data-fixed]').forEach(b=>b.onclick=()=>{ps.fixedMat=b.dataset.fixed;drawWidget(w)});
 w.querySelectorAll('[data-pontic]').forEach(b=>b.onclick=()=>{ps.pontic=b.dataset.pontic;drawWidget(w)});
 w.querySelectorAll('[data-tooth]').forEach(b=>b.onclick=()=>{let t=Number(b.dataset.tooth);if(ps.tab==='diag'){let set=U.includes(t)?ps.up:ps.lo;set.has(t)?set.delete(t):set.add(t)}else markTooth(t);drawWidget(w)});
}
function addProsthoWidget(){const host=document.querySelector('#sheet-content');if(!host)return;const w=document.createElement('div');w.className='prostho-widget';w.innerHTML=`<h4>🦷 Diseñador protésico educativo</h4><div class="prostho-tabs"><button data-tab="diag">Kennedy</button><button data-tab="rpd">PPR</button><button data-tab="complete">Total</button><button data-tab="fixed">Fija</button></div><div class="prostho-body"></div>`;host.appendChild(w);drawWidget(w)}
const baseProstRender=renderSheet;renderSheet=function(k){baseProstRender(k);if(k==='protesis')addProsthoWidget()};renderSheet('ingreso');
})();